{
  "hash": "20255b09a6eddd7c65075b9e2a150982",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"How long until building complaints are dispositioned? A survival analysis case study\"\ncategories:\n  - statistical analysis\n  - survival analysis\ntype: learn-subsection\nweight: 9\ndescription: | \n  Learn how to use tidymodels for survival analysis.\ntoc: true\ntoc-depth: 2\ninclude-after-body: ../../../resources.html\n---\n\n\n\n\n\n\n## Introduction\n\nTo use code in this article,  you will need to install the following packages: censored and tidymodels.\n\nSurvival analysis is a field of statistics and machine learning for analyzing the time to an event. While it has its roots in medical research, the event of interest can be anything from customer churn to machine failure. Methods from survival analysis take into account that some observations may not yet have experienced the event of interest and are thus censored. \n\nHere we want to predict the time it takes for a complaint to be dispositioned by the Department of Buildings in New York City. We are going to walk through a complete analysis from beginning to end, showing how to analyze time-to-event data.\n\nLet's start with loading the censored package, the parnsip extension for survival analysis models.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(censored)\n#> Loading required package: survival\n```\n:::\n\n\n## The buildings complaints data\n\nThe city of New York publishes data on the [complaints](https://data.cityofnewyork.us/Housing-Development/DOB-Complaints-Received/eabe-havv/about_data) received by the Department of Buildings. The data includes information on the type of complaint, the date it was entered in their records, the date it was dispositioned, and the location of the building the complaint was about. We are using a subset of the data, available in the modeldatatoo package.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata(building_complaints, package = \"modeldatatoo\")\nglimpse(building_complaints)\n#> Rows: 4,235\n#> Columns: 11\n#> $ days_to_disposition <dbl> 72, 1, 41, 45, 16, 62, 56, 11, 35, 38, 39, 106, 1,…\n#> $ status              <chr> \"ACTIVE\", \"ACTIVE\", \"ACTIVE\", \"ACTIVE\", \"ACTIVE\", …\n#> $ year_entered        <fct> 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 20…\n#> $ latitude            <dbl> 40.66173, 40.57668, 40.73242, 40.68245, 40.63156, …\n#> $ longitude           <dbl> -73.98297, -74.00453, -73.87630, -73.79367, -73.99…\n#> $ borough             <fct> Brooklyn, Brooklyn, Queens, Queens, Brooklyn, Quee…\n#> $ special_district    <fct> None, None, None, None, None, None, None, None, No…\n#> $ unit                <fct> Q-L, Q-L, SPOPS, Q-L, BKLYN, Q-L, Q-L, SPOPS, Q-L,…\n#> $ community_board     <fct> 307, 313, 404, 412, 312, 406, 306, 306, 409, 404, …\n#> $ complaint_category  <fct> 45, 45, 49, 45, 31, 45, 45, 49, 45, 45, 45, 4A, 31…\n#> $ complaint_priority  <fct> B, B, C, B, C, B, B, C, B, B, B, B, C, C, B, B, B,…\n```\n:::\n\n\nBefore we dive into survival analysis, let's get a impression of how the complaints are distributed across the city. We have complaints in all five boroughs, albeit with a somewhat lower density of complaints in Staten Island.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Building complaints in New York City](nyc_building_complaints.png){fig-align='center' fig-alt='A scatter plot of building complaint locations superimposed on a street map. Complaints are raised in all five boroughs.' width=100%}\n:::\n:::\n\n\nIn the dataset, we can see the `days_to_disposition` as well as the `status` of the complaint. For a complaint with status `\"ACTIVE\"`, the time to disposition is censored, meaning we do know that is has taken at least that long, but not how long it will have taken eventually. \n\nThe standard form for time-to-event data are `Surv` objects which capture the time as well as the event status. As with all transformations of the response, it is advisable to do this before heading into the model fitting process with tidymodels.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbuilding_complaints <- building_complaints %>% \n  mutate(\n    disposition_surv = Surv(days_to_disposition, status == \"CLOSED\"), \n    .keep = \"unused\"\n  )\n```\n:::\n\n\n## Data splitting and resampling\n\nFor our resampling strategy, let's use a 3-way split into training, validation, and test set.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(403)\ncomplaints_split <- initial_validation_split(building_complaints)\n```\n:::\n\n\nFirst, let's pull out the training data and have a brief look at the response.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncomplaints_train <- training(complaints_split)\n\nsurvfit(disposition_surv ~ 1, data = complaints_train) %>% plot()\n```\n\n::: {.cell-output-display}\n![](figs/unnamed-chunk-7-1.svg){fig-align='center' fig-alt='A Kaplan-Meier curve dropping rapidly initially, then reaching about 10% survival rate at around 100 days, and finally trailing off until about 400 days.' width=672}\n:::\n:::\n\n\nWe can see that the majority of complaints is dispositioned relatively quickly, but some complaints are still active after 100 days.\n\n## A first model\n\nThe censored package includes parametric, semi-parametric, and tree-based models for this type of analysis. To start, we are fitting a parametric survival model with the default of assuming a Weibull distribution on the time to disposition. We'll explore the more flexible models once we have a sense of how well this more restrictive model performs on this dataset.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nspec_survreg <- survival_reg() %>% \n  set_engine(\"survival\") %>% \n  set_mode(\"censored regression\")\n```\n:::\n\n\nWe have several missing values in `complaint_priority` that we are turning into a separate category, `\"unknown\"`. We are also combining the less common categories for `community_board` and `unit` into an `\"other\"` category to reduce the number of levels in the predictors. The complaint category often does not tell us much more than the unit, with several complaint categories being handled by a specific unit only. This can lead to the model being unable to estimate some of the coefficients. Since our goal here is only to get a rough idea of how well the model performs, we are removing the complaint category for now.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrec_other <- recipe(disposition_surv ~ ., data = complaints_train) %>% \n  step_unknown(complaint_priority) %>% \n  step_rm(complaint_category) %>% \n  step_novel(community_board, unit) %>%\n  step_other(community_board, unit, threshold = 0.02)\n```\n:::\n\n\nWe combine the recipe and the model into a workflow. This allows us to easily resample the model because all preprocessing steps are applied to the training set and the validation set for us.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwflow_survreg <- workflow() %>% \n  add_recipe(rec_other) %>% \n  add_model(spec_survreg)\n```\n:::\n\n\nLet's access the resampling set from the initial split and fit the model. We are calculating several different performance metrics here: the Brier score, its integrated version, the area under the ROC curve, and the concordance index. Note that all of these are used in a version tailored to survival analysis. The concordance index uses the predicted event time to measure the model's ability to rank the observations correctly. The Brier score and the ROC curve use the predicted probability of survival at a given time point. We are evaluating these metrics every 30 days up to 300 days, as provided in the `eval_time` argument. The Brier score is a measure of the accuracy of the predicted probabilities while the ROC curve is a measure of the model's ability to discriminate between events and non-events at the given time point. Because these metrics are defined \"at a given time point\" they are also referred to as dynamic metrics. \n\n::: {.callout-tip}\nFor more information see the [Dynamic Performance Metrics for Event Time Data](../survival-metrics/) article.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncomplaints_rset <- validation_set(complaints_split)\n\nset.seed(1)\nres_survreg <- fit_resamples(\n  wflow_survreg,\n  complaints_rset,\n  metrics = metric_set(brier_survival_integrated, brier_survival, roc_auc_survival,\n                       concordance_survival),\n  eval_time = seq(0, 300, 30), \n  control = control_resamples(save_workflow = TRUE, save_pred = TRUE)\n)\n```\n:::\n\n\nSo how do predictions from censored regression models look like?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npreds <- collect_predictions(res_survreg)\npreds\n#> # A tibble: 847 × 6\n#>    .pred             .pred_time id          .row disposition_surv .config       \n#>    <list>                 <dbl> <chr>      <int>           <Surv> <chr>         \n#>  1 <tibble [11 × 3]>       93.3 validation  2542              35+ Preprocessor1…\n#>  2 <tibble [11 × 3]>       16.6 validation  2543             129+ Preprocessor1…\n#>  3 <tibble [11 × 3]>       30.1 validation  2544               4+ Preprocessor1…\n#>  4 <tibble [11 × 3]>       33.8 validation  2545               5+ Preprocessor1…\n#>  5 <tibble [11 × 3]>       22.7 validation  2546               1+ Preprocessor1…\n#>  6 <tibble [11 × 3]>       55.6 validation  2547              76+ Preprocessor1…\n#>  7 <tibble [11 × 3]>       69.6 validation  2548              51+ Preprocessor1…\n#>  8 <tibble [11 × 3]>       95.2 validation  2549              44+ Preprocessor1…\n#>  9 <tibble [11 × 3]>       50.0 validation  2550              15+ Preprocessor1…\n#> 10 <tibble [11 × 3]>       30.1 validation  2551              61+ Preprocessor1…\n#> # ℹ 837 more rows\n```\n:::\n\n\nThe predicted survival time is in the `.pred_time` column and the predicted survival probabilities are in the `.pred` list column. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npreds$.pred[[6]]\n#> # A tibble: 11 × 3\n#>    .eval_time .pred_survival .weight_censored\n#>         <dbl>          <dbl>            <dbl>\n#>  1          0         1                  1   \n#>  2         30         0.541              1.04\n#>  3         60         0.345              1.18\n#>  4         90         0.231             NA   \n#>  5        120         0.159             NA   \n#>  6        150         0.111             NA   \n#>  7        180         0.0790            NA   \n#>  8        210         0.0568            NA   \n#>  9        240         0.0413            NA   \n#> 10        270         0.0302            NA   \n#> 11        300         0.0223            NA\n```\n:::\n\n\nFor each observation, `.pred` contains a tibble with the evaluation time `.eval_time` and the corresponding survival probability `.pred_survival`. The column `.weight_censored` contains the weights used in the calculation of the dynamic performance metrics. \n\n::: {.callout-tip}\nFor details on the weights see the [Accounting for Censoring in Performance Metrics for Event Time Data](../survival-metrics-details/) article.\n:::\n\nOf the metrics we calculated with these predictions, let's take a look at the AUC ROC first.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncollect_metrics(res_survreg) %>% \n  filter(.metric == \"roc_auc_survival\")\n#> # A tibble: 11 × 7\n#>    .metric          .estimator .eval_time  mean     n std_err .config           \n#>    <chr>            <chr>           <dbl> <dbl> <int>   <dbl> <chr>             \n#>  1 roc_auc_survival standard            0 0.5       1      NA Preprocessor1_Mod…\n#>  2 roc_auc_survival standard           30 0.823     1      NA Preprocessor1_Mod…\n#>  3 roc_auc_survival standard           60 0.781     1      NA Preprocessor1_Mod…\n#>  4 roc_auc_survival standard           90 0.766     1      NA Preprocessor1_Mod…\n#>  5 roc_auc_survival standard          120 0.715     1      NA Preprocessor1_Mod…\n#>  6 roc_auc_survival standard          150 0.736     1      NA Preprocessor1_Mod…\n#>  7 roc_auc_survival standard          180 0.748     1      NA Preprocessor1_Mod…\n#>  8 roc_auc_survival standard          210 0.814     1      NA Preprocessor1_Mod…\n#>  9 roc_auc_survival standard          240 0.838     1      NA Preprocessor1_Mod…\n#> 10 roc_auc_survival standard          270 0.803     1      NA Preprocessor1_Mod…\n#> 11 roc_auc_survival standard          300 0.789     1      NA Preprocessor1_Mod…\n```\n:::\n\n\nWe can discriminate between events and non-events reasonably well, especially in the first 30 and 60 days. How about the probabilities that the categorization into event and non-event is based on? \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncollect_metrics(res_survreg) %>% \n  filter(.metric %in% c(\"brier_survival_integrated\", \"brier_survival\"))\n#> # A tibble: 12 × 7\n#>    .metric                   .estimator .eval_time    mean     n std_err .config\n#>    <chr>                     <chr>           <dbl>   <dbl> <int>   <dbl> <chr>  \n#>  1 brier_survival            standard            0 0           1      NA Prepro…\n#>  2 brier_survival            standard           30 0.163       1      NA Prepro…\n#>  3 brier_survival            standard           60 0.122       1      NA Prepro…\n#>  4 brier_survival            standard           90 0.0722      1      NA Prepro…\n#>  5 brier_survival            standard          120 0.0485      1      NA Prepro…\n#>  6 brier_survival            standard          150 0.0292      1      NA Prepro…\n#>  7 brier_survival            standard          180 0.0253      1      NA Prepro…\n#>  8 brier_survival            standard          210 0.0213      1      NA Prepro…\n#>  9 brier_survival            standard          240 0.0132      1      NA Prepro…\n#> 10 brier_survival            standard          270 0.0107      1      NA Prepro…\n#> 11 brier_survival            standard          300 0.00561     1      NA Prepro…\n#> 12 brier_survival_integrated standard           NA 0.0508      1      NA Prepro…\n```\n:::\n\n\nThe accuracy of the predicted probabilities is generally good, albeit lowest for evaluation times of 30 and 60 days. The integrated Brier score is a measure of the overall accuracy of the predicted probabilities. \n\nWhich metric to optimise for depends on whether separation or calibration is more important in the modeling problem at hand. We'll go with calibration here. Since we don't have a particular evaluation time that we want to predict well at, we are going to use the integrated Brier score as our main performance metric.\n\n## Try out more models\n\nLumping factor levels together based on frequencies can lead to a loss of information so let's also try some different approaches. We can let a random forest model group the factor levels via the tree splits. Alternatively, we can turn the factors into dummy variables and use a regularized model to select relevant factor levels.\n\nFirst, we are creating the recipes for these two approaches.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrec_unknown <- recipe(disposition_surv ~ ., data = complaints_train) %>% \n  step_unknown(complaint_priority) \n\nrec_dummies <- rec_unknown %>% \n  step_novel(all_nominal_predictors()) %>%\n  step_dummy(all_nominal_predictors()) %>% \n  step_zv(all_predictors()) %>% \n  step_normalize(all_numeric_predictors())\n```\n:::\n\n\nNext, we are creating the model specifications and tagging several hyperparameters for tuning. \nFor the random forest, we are using the `\"aorsf\"` engine for accelerated oblique random survival forests. An oblique tree can split on linear combinations of the predictors, i.e., it provides more flexibility in the splits than a tree which splits on a single predictor.\nFor the regularized model, we are using the `\"glmnet\"` engine for a semi-parametric Cox proportional hazards model.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nspec_oblique <- rand_forest(mtry = tune(), min_n = tune()) %>% \n  set_engine(\"aorsf\") %>% \n  set_mode(\"censored regression\")\n\nwflow_oblique <- workflow() %>% \n  add_recipe(rec_unknown) %>% \n  add_model(spec_oblique)\n\nspec_coxnet <- proportional_hazards(penalty = tune()) %>% \n  set_engine(\"glmnet\") %>% \n  set_mode(\"censored regression\")\n\nwflow_coxnet <- workflow() %>% \n  add_recipe(rec_dummies) %>% \n  add_model(spec_coxnet)\n```\n:::\n\n\nWe can tune workflows with any of the `tune_*()` functions such as `tune_grid()` for grid search or `tune_bayes()` for Bayesian optimization. Here we are using grid search for simplicity.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(1)\nres_oblique <- tune_grid(\n  wflow_oblique,\n  complaints_rset,\n  grid = 10,\n  metrics = metric_set(brier_survival_integrated, brier_survival, roc_auc_survival, concordance_survival),\n  eval_time = seq(0, 300, 30), \n  control = control_grid(save_workflow = TRUE)\n)\n#> i Creating pre-processing data to finalize unknown parameter: mtry\n\nset.seed(1)\nres_coxnet <- tune_grid(\n  wflow_coxnet,\n  complaints_rset,\n  grid = 10,\n  metrics = metric_set(brier_survival_integrated, brier_survival, roc_auc_survival, concordance_survival),\n  eval_time = seq(0, 300, 30), \n  control = control_grid(save_workflow = TRUE)\n)\n```\n:::\n\n\nSo do any of these models perform better than the parametric survival model?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nshow_best(res_oblique, metric = \"brier_survival_integrated\", n = 5)\n#> # A tibble: 5 × 9\n#>    mtry min_n .metric         .estimator .eval_time   mean     n std_err .config\n#>   <int> <int> <chr>           <chr>           <dbl>  <dbl> <int>   <dbl> <chr>  \n#> 1     8    16 brier_survival… standard           NA 0.0462     1      NA Prepro…\n#> 2     4     6 brier_survival… standard           NA 0.0463     1      NA Prepro…\n#> 3     6    23 brier_survival… standard           NA 0.0465     1      NA Prepro…\n#> 4     7    26 brier_survival… standard           NA 0.0465     1      NA Prepro…\n#> 5     9    38 brier_survival… standard           NA 0.0466     1      NA Prepro…\n\nshow_best(res_coxnet, metric = \"brier_survival_integrated\", n = 5)\n#> # A tibble: 5 × 8\n#>         penalty .metric       .estimator .eval_time   mean     n std_err .config\n#>           <dbl> <chr>         <chr>           <dbl>  <dbl> <int>   <dbl> <chr>  \n#> 1 0.00750       brier_surviv… standard           NA 0.0482     1      NA Prepro…\n#> 2 0.000000262   brier_surviv… standard           NA 0.0487     1      NA Prepro…\n#> 3 0.0000000591  brier_surviv… standard           NA 0.0487     1      NA Prepro…\n#> 4 0.00000000200 brier_surviv… standard           NA 0.0487     1      NA Prepro…\n#> 5 0.0000588     brier_surviv… standard           NA 0.0487     1      NA Prepro…\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nThe best regularized Cox model performs a little better than the parametric survival model, with an integrated Brier score of 0.0482 compared to 0.0508 for the parametric model. The random forest performs yet a little better with an integrated Brier score of 0.0462.\n\n## The final model\n\nWe chose the random forest model as the final model. So let's finalize the workflow by replacing the `tune()` placeholders with the best hyperparameters.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nparam_best <- select_best(res_oblique, metric = \"brier_survival_integrated\")\n\nwflow_oblique_best <- finalize_workflow(\n  wflow_oblique,\n  param_best\n)\n```\n:::\n\n\nWe can now fit the final model on the training data and evaluate it on the test data.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(2)\nfit_oblique <- last_fit(\n  wflow_oblique_best, \n  complaints_split,\n  metrics = metric_set(brier_survival_integrated, brier_survival, roc_auc_survival, concordance_survival),\n  eval_time = seq(0, 300, 30)\n)\n\ncollect_metrics(fit_oblique) %>% \n  filter(.metric == \"brier_survival_integrated\")\n#> # A tibble: 1 × 5\n#>   .metric                   .estimator .estimate .eval_time .config             \n#>   <chr>                     <chr>          <dbl>      <dbl> <chr>               \n#> 1 brier_survival_integrated standard      0.0412         NA Preprocessor1_Model1\n```\n:::\n\n\nWe can extract the fitted workflow to either predict directly on new data or deploy the model.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncomplaints_model <- extract_workflow(fit_oblique)\n\ncomplaints_5 <- testing(complaints_split) %>% slice(1:5)\n\npredict(complaints_model, new_data = complaints_5, type = \"time\")\n#> # A tibble: 5 × 1\n#>   .pred_time\n#>        <dbl>\n#> 1       70.4\n#> 2       37.2\n#> 3       81.5\n#> 4       66.6\n#> 5       32.5\n```\n:::\n\n\nFor more information on survival analysis with tidymodels see the [`survival analysis` tag](https://www.tidymodels.org/learn/index.html#category=survival%20analysis).\n\n## Session information {#session-info}\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> ─ Session info ─────────────────────────────────────────────────────\n#>  setting  value\n#>  version  R version 4.3.2 (2023-10-31)\n#>  os       macOS Sonoma 14.3.1\n#>  system   aarch64, darwin20\n#>  ui       X11\n#>  language (EN)\n#>  collate  en_US.UTF-8\n#>  ctype    en_US.UTF-8\n#>  tz       Europe/London\n#>  date     2024-03-27\n#>  pandoc   3.1.12.3 @ /opt/homebrew/bin/ (via rmarkdown)\n#> \n#> ─ Packages ─────────────────────────────────────────────────────────\n#>  package    * version date (UTC) lib source\n#>  broom      * 1.0.5   2023-06-09 [1] CRAN (R 4.3.0)\n#>  censored   * 0.3.0   2024-01-31 [1] CRAN (R 4.3.1)\n#>  dials      * 1.2.1   2024-02-22 [1] CRAN (R 4.3.1)\n#>  dplyr      * 1.1.4   2023-11-17 [1] CRAN (R 4.3.1)\n#>  ggplot2    * 3.5.0   2024-02-23 [1] CRAN (R 4.3.1)\n#>  infer      * 1.0.6   2024-01-31 [1] CRAN (R 4.3.1)\n#>  parsnip    * 1.2.1   2024-03-22 [1] CRAN (R 4.3.1)\n#>  purrr      * 1.0.2   2023-08-10 [1] CRAN (R 4.3.0)\n#>  recipes    * 1.0.10  2024-02-18 [1] CRAN (R 4.3.1)\n#>  rlang        1.1.3   2024-01-10 [1] CRAN (R 4.3.1)\n#>  rsample    * 1.2.1   2024-03-25 [1] CRAN (R 4.3.2)\n#>  tibble     * 3.2.1   2023-03-20 [1] CRAN (R 4.3.0)\n#>  tidymodels * 1.1.1   2023-08-24 [1] CRAN (R 4.3.1)\n#>  tune       * 1.2.0   2024-03-20 [1] CRAN (R 4.3.1)\n#>  workflows  * 1.1.4   2024-02-19 [1] CRAN (R 4.3.1)\n#>  yardstick  * 1.3.1   2024-03-21 [1] CRAN (R 4.3.1)\n#> \n#>  [1] /Users/hannah/Library/R/arm64/4.3/library\n#>  [2] /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library\n#> \n#> ────────────────────────────────────────────────────────────────────\n```\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}