---
title: Learn
description: "Learn how to go farther with tidymodels in your modeling and machine learning projects."
icon_attribution: "Icons made by [Becris](https://www.flaticon.com/authors/becris) from www.flaticon.com"
---

After you know [what you need to get started](/start/) with tidymodels, you can learn more and go further. Find articles here to help you solve specific problems using the tidymodels framework. Articles are organized into four categories:

## Perform Statistical Analyses

 - [Correlation and regression fundamentals with tidy data principles](statistics/tidy-analysis/correlation_and_regression_fundamentals_with_tidy_data_principles.html): Analyze the results of correlation tests and simple regression models for many data sets at once
 - [K-means clustering with tidy data principles](statistics/k-means/k-means_clustering_with_tidy_data_principles.html): Summarize clustering characteristics and estimate the best number of clusters for a data set.
 - [Bootstrap resampling and tidy regression models](statistics/bootstrap/bootstrap_resampling_and_tidy_regression_models.html): Apply bootstrap resampling to estimate uncertainty in model parameters.
 - [Hypothesis testing using resampling and tidy data](statistics/infer/hypothesis_testing_using_resampling_and_tidy_data.html):  Perform common hypothesis tests for statistical inference using flexible functions.
 - [Statistical analysis of contingency tables](statistics/xtabs/statistical_analysis_of_contingency_tables.html):  Use tests of independence and goodness of fit to analyze tables of counts.

## Create Robust Models

 - [Regression models two ways](models/parsnip-ranger-glmnet/regression_models_two_ways.html): Create and train different kinds of regression models with different computational engines.
 - [Classification models using a neural network](models/parsnip-nnet/classification_models_using_a_neural_network.html): Train a classification model and evaluate its performance.
 - [Subsampling for class imbalances](models/sub-sampling/subsampling_for_class_imbalances.html): Improve model performance in imbalanced data sets through undersampling or oversampling.
 - [Modeling time series with tidy resampling](models/time-series/modeling_time_series_with_tidy_resampling.html): Calculate performance estimates for time series forecasts using resampling.
 - [Working with model coefficients](models/coefficients/working_with_model_coefficients.html): Create models that use coefficients, extract them from fitted models, and visualize them.


## Tune, Compare, and Work with Your Models

 - [Model tuning via grid search](work/tune-svm/model_tuning_via_grid_search.html): Choose hyperparameters for a model by training on a grid of many possible parameter values.
 - [Nested resampling](work/nested-resampling/nested_resampling.html): Estimate the best hyperparameters for a model using nested resampling.
 - [Iterative Bayesian optimization of a classification model](work/bayes-opt/iterative_bayesian_optimization_of_a_classification_model.html): Identify the best hyperparameters for a model using Bayesian optimization of iterative search.
 - [Tuning text models](work/tune-text/tuning_text_models.html): Prepare text data for predictive modeling and tune with both grid and iterative search.
 - [Creating case weights based on time](work/case-weights/creating_case_weights_based_on_time.html): Create models that use coefficients, extract them from fitted models, and visualize them.


## Create Custom Modeling Tools

 - [Create your own recipe step function](develop/recipes/create_your_own_recipe_step_function.html): Write a new recipe step for data preprocessing.
 - [How to build a parsnip model](develop/models/how_to_build_a_parsnip_model.html): Create a parsnip model function from an existing model implementation.
 - [Custom performance metrics](develop/metrics/custom_performance_metrics.html): Create a new performance metric and integrate it with yardstick functions.
 - [How to create a tuning parameter function](develop/parameters/how_to_create_a_tuning_parameter_function.html): Build functions to use in tuning both quantitative and qualitative parameters.
 - [Create your own broom tidier methods](develop/broom/create_your_own_broom_tidier_methods.html): Write `tidy()`, `glance()`, and `augment()` methods for new model objects.
 
 
 
 