<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Develop, from beginning to end, a predictive model using best practices.">
<title>A predictive modeling case study – tidymodels</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>
<script src="../../site_libs/quarto-nav/quarto-nav.js"></script><script src="../../site_libs/clipboard/clipboard.min.js"></script><script src="../../site_libs/quarto-search/autocomplete.umd.js"></script><script src="../../site_libs/quarto-search/fuse.min.js"></script><script src="../../site_libs/quarto-search/quarto-search.js"></script><meta name="quarto:offset" content="../../">
<link href="../../favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script><script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script><script src="../../site_libs/quarto-html/popper.min.js"></script><script src="../../site_libs/quarto-html/tippy.umd.min.js"></script><script src="../../site_libs/quarto-html/anchor.min.js"></script><link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-a9c94084e156453ce75ecc8ff7b2041c.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script><link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-8348b2d5c2bb4a73246cdd5819180553.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><link rel="stylesheet" href="../styles.css">
</head>
<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">tidymodels</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item">
    <a class="nav-link" href="../../packages/index.html"> 
<span class="menu-text">Packages</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../start/index.html" aria-current="page"> 
<span class="menu-text">Get Started</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../learn/index.html"> 
<span class="menu-text">Learn</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../help/index.html"> 
<span class="menu-text">Help</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../contribute/index.html"> 
<span class="menu-text">Contribute</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about/index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../find/index.html"> 
<span class="menu-text">Find</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/tidymodels/"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../start/case-study/index.html">A predictive modeling case study</a></li></ol></nav><a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../start/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GET STARTED</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../start/models/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Build a model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../start/recipes/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preprocess your data with recipes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../start/resampling/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Evaluate your model with resamples</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../start/tuning/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tune model parameters</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../start/case-study/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">A predictive modeling case study</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">A predictive modeling case study</h1>
  <div class="quarto-categories">
    <div class="quarto-category">model fitting</div>
    <div class="quarto-category">tuning</div>
    <div class="quarto-category">parsnip</div>
    <div class="quarto-category">recipes</div>
    <div class="quarto-category">rsample</div>
    <div class="quarto-category">workflows</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>Develop, from beginning to end, a predictive model using best practices.</p>
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><nav id="TOC" role="doc-toc"><ul>
<li><a href="#intro" id="toc-intro">Introduction</a></li>
  <li><a href="#data" id="toc-data">The Hotel Bookings Data</a></li>
  <li><a href="#data-split" id="toc-data-split">Data Splitting &amp; Resampling</a></li>
  <li><a href="#first-model" id="toc-first-model">A first model: penalized logistic regression</a></li>
  <li><a href="#second-model" id="toc-second-model">A second model: tree-based ensemble</a></li>
  <li><a href="#last-fit" id="toc-last-fit">The last fit</a></li>
  <li><a href="#next" id="toc-next">Where to next?</a></li>
  <li><a href="#session-info" id="toc-session-info">Session information</a></li>
  </ul>
<div class="toc-actions"><ul>
<li><a href="https://github.com/tidymodels/tidymodels.org/edit/main/start/case-study/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li>
<li><a href="https://github.com/tidymodels/tidymodels.org/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li>
</ul></div></nav><section id="intro" class="level2"><h2 class="anchored" data-anchor-id="intro">Introduction</h2>
<p>Each of the four previous <a href="../../start/"><em>Get Started</em></a> articles has focused on a single task related to modeling. Along the way, we also introduced core packages in the tidymodels ecosystem and some of the key functions you’ll need to start working with models. In this final case study, we will use all of the previous articles as a foundation to build a predictive model from beginning to end with data on hotel stays.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="img/hotel.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>To use code in this article, you will need to install the following packages: glmnet, here, ranger, readr, scales, tidymodels, and vip.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidymodels.tidymodels.org">tidymodels</a></span><span class="op">)</span>  </span>
<span></span>
<span><span class="co"># Helper packages</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://readr.tidyverse.org">readr</a></span><span class="op">)</span>       <span class="co"># for importing data</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/koalaverse/vip/">vip</a></span><span class="op">)</span>         <span class="co"># for variable importance plots</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p><a href="https://rstudio.cloud/project/2674862">Test Drive</a></p>
</section><section id="data" class="level2"><h2 class="anchored" data-anchor-id="data">The Hotel Bookings Data</h2>
<p>Let’s use hotel bookings data from <a href="https://doi.org/10.1016/j.dib.2018.11.126">Antonio, Almeida, and Nunes (2019)</a> to predict which hotel stays included children and/or babies, based on the other characteristics of the stays such as which hotel the guests stay at, how much they pay, etc. This was also a <a href="https://github.com/rfordatascience/tidytuesday/tree/master/data/2020/2020-02-11"><code>#TidyTuesday</code></a> dataset with a <a href="https://github.com/rfordatascience/tidytuesday/tree/master/data/2020/2020-02-11#data-dictionary">data dictionary</a> you may want to look over to learn more about the variables. We’ll use a slightly <a href="https://gist.github.com/topepo/05a74916c343e57a71c51d6bc32a21ce">edited version of the dataset</a> for this case study.</p>
<p>To start, let’s read our hotel data into R, which we’ll do by providing <a href="https://readr.tidyverse.org/reference/read_delim.html"><code>readr::read_csv()</code></a> with a url where our CSV data is located (“<a href="https://tidymodels.org/start/case-study/hotels.csv" class="uri">https://tidymodels.org/start/case-study/hotels.csv</a>”):</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidymodels.tidymodels.org">tidymodels</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://readr.tidyverse.org">readr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">hotels</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu">read_csv</span><span class="op">(</span><span class="st">"https://tidymodels.org/start/case-study/hotels.csv"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/across.html">across</a></span><span class="op">(</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/where.html">where</a></span><span class="op">(</span><span class="va">is.character</span><span class="op">)</span>, <span class="va">as.factor</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">hotels</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 50000    23</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>In the original paper, the <a href="https://doi.org/10.1016/j.dib.2018.11.126">authors</a> caution that the distribution of many variables (such as number of adults/children, room type, meals bought, country of origin of the guests, and so forth) is different for hotel stays that were canceled versus not canceled. This makes sense because much of that information is gathered (or gathered again more accurately) when guests check in for their stay, so canceled bookings are likely to have more missing data than non-canceled bookings, and/or to have different characteristics when data is not missing. Given this, it is unlikely that we can reliably detect meaningful differences between guests who cancel their bookings and those who do not with this dataset. To build our models here, we have already filtered the data to include only the bookings that did not cancel, so we’ll be analyzing <em>hotel stays</em> only.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">hotels</span><span class="op">)</span></span>
<span><span class="co">#&gt; Rows: 50,000</span></span>
<span><span class="co">#&gt; Columns: 23</span></span>
<span><span class="co">#&gt; $ hotel                          &lt;fct&gt; City_Hotel, City_Hotel, Resort_Hotel, R…</span></span>
<span><span class="co">#&gt; $ lead_time                      &lt;dbl&gt; 217, 2, 95, 143, 136, 67, 47, 56, 80, 6…</span></span>
<span><span class="co">#&gt; $ stays_in_weekend_nights        &lt;dbl&gt; 1, 0, 2, 2, 1, 2, 0, 0, 0, 2, 1, 0, 1, …</span></span>
<span><span class="co">#&gt; $ stays_in_week_nights           &lt;dbl&gt; 3, 1, 5, 6, 4, 2, 2, 3, 4, 2, 2, 1, 2, …</span></span>
<span><span class="co">#&gt; $ adults                         &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, …</span></span>
<span><span class="co">#&gt; $ children                       &lt;fct&gt; none, none, none, none, none, none, chi…</span></span>
<span><span class="co">#&gt; $ meal                           &lt;fct&gt; BB, BB, BB, HB, HB, SC, BB, BB, BB, BB,…</span></span>
<span><span class="co">#&gt; $ country                        &lt;fct&gt; DEU, PRT, GBR, ROU, PRT, GBR, ESP, ESP,…</span></span>
<span><span class="co">#&gt; $ market_segment                 &lt;fct&gt; Offline_TA/TO, Direct, Online_TA, Onlin…</span></span>
<span><span class="co">#&gt; $ distribution_channel           &lt;fct&gt; TA/TO, Direct, TA/TO, TA/TO, Direct, TA…</span></span>
<span><span class="co">#&gt; $ is_repeated_guest              &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ previous_cancellations         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ previous_bookings_not_canceled &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ reserved_room_type             &lt;fct&gt; A, D, A, A, F, A, C, B, D, A, A, D, A, …</span></span>
<span><span class="co">#&gt; $ assigned_room_type             &lt;fct&gt; A, K, A, A, F, A, C, A, D, A, D, D, A, …</span></span>
<span><span class="co">#&gt; $ booking_changes                &lt;dbl&gt; 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ deposit_type                   &lt;fct&gt; No_Deposit, No_Deposit, No_Deposit, No_…</span></span>
<span><span class="co">#&gt; $ days_in_waiting_list           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ customer_type                  &lt;fct&gt; Transient-Party, Transient, Transient, …</span></span>
<span><span class="co">#&gt; $ average_daily_rate             &lt;dbl&gt; 80.75, 170.00, 8.00, 81.00, 157.60, 49.…</span></span>
<span><span class="co">#&gt; $ required_car_parking_spaces    &lt;fct&gt; none, none, none, none, none, none, non…</span></span>
<span><span class="co">#&gt; $ total_of_special_requests      &lt;dbl&gt; 1, 3, 2, 1, 4, 1, 1, 1, 1, 1, 0, 1, 0, …</span></span>
<span><span class="co">#&gt; $ arrival_date                   &lt;date&gt; 2016-09-01, 2017-08-25, 2016-11-19, 20…</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>We will build a model to predict which actual hotel stays included children and/or babies, and which did not. Our outcome variable <code>children</code> is a factor variable with two levels:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">hotels</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">children</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>prop <span class="op">=</span> <span class="va">n</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 3</span></span>
<span><span class="co">#&gt;   children     n   prop</span></span>
<span><span class="co">#&gt;   &lt;fct&gt;    &lt;int&gt;  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 children  4038 0.0808</span></span>
<span><span class="co">#&gt; 2 none     45962 0.919</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>We can see that children were only in 8.1% of the reservations. This type of class imbalance can often wreak havoc on an analysis. While there are several methods for combating this issue using <a href="../../find/recipes/">recipes</a> (search for steps to <code>upsample</code> or <code>downsample</code>) or other more specialized packages like <a href="https://themis.tidymodels.org/">themis</a>, the analyses shown below analyze the data as-is.</p>
</section><section id="data-split" class="level2"><h2 class="anchored" data-anchor-id="data-split">Data Splitting &amp; Resampling</h2>
<p>For a data splitting strategy, let’s reserve 25% of the stays to the test set. As in our <a href="../../start/resampling/#data-split"><em>Evaluate your model with resampling</em></a> article, we know our outcome variable <code>children</code> is pretty imbalanced so we’ll use a stratified random sample:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span>
<span><span class="va">splits</span>      <span class="op">&lt;-</span> <span class="fu"><a href="https://rsample.tidymodels.org/reference/initial_split.html">initial_split</a></span><span class="op">(</span><span class="va">hotels</span>, strata <span class="op">=</span> <span class="va">children</span><span class="op">)</span></span>
<span></span>
<span><span class="va">hotel_other</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rsample.tidymodels.org/reference/initial_split.html">training</a></span><span class="op">(</span><span class="va">splits</span><span class="op">)</span></span>
<span><span class="va">hotel_test</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rsample.tidymodels.org/reference/initial_split.html">testing</a></span><span class="op">(</span><span class="va">splits</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># training set proportions by children</span></span>
<span><span class="va">hotel_other</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">children</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>prop <span class="op">=</span> <span class="va">n</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 3</span></span>
<span><span class="co">#&gt;   children     n   prop</span></span>
<span><span class="co">#&gt;   &lt;fct&gt;    &lt;int&gt;  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 children  3027 0.0807</span></span>
<span><span class="co">#&gt; 2 none     34473 0.919</span></span>
<span></span>
<span><span class="co"># test set proportions by children</span></span>
<span><span class="va">hotel_test</span>  <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">children</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>prop <span class="op">=</span> <span class="va">n</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 3</span></span>
<span><span class="co">#&gt;   children     n   prop</span></span>
<span><span class="co">#&gt;   &lt;fct&gt;    &lt;int&gt;  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 children  1011 0.0809</span></span>
<span><span class="co">#&gt; 2 none     11489 0.919</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>In our articles so far, we’ve relied on 10-fold cross-validation as the primary resampling method using <a href="https://rsample.tidymodels.org/reference/vfold_cv.html"><code>rsample::vfold_cv()</code></a>. This has created 10 different resamples of the training set (which we further split into <em>analysis</em> and <em>assessment</em> sets), producing 10 different performance metrics that we then aggregated.</p>
<p>For this case study, rather than using multiple iterations of resampling, let’s create a single resample called a <em>validation set</em>. In tidymodels, a validation set is treated as a single iteration of resampling. This will be a split from the 37,500 stays that were not used for testing, which we called <code>hotel_other</code>. This split creates two new datasets:</p>
<ul>
<li><p>the set held out for the purpose of measuring performance, called the <em>validation set</em>, and</p></li>
<li><p>the remaining data used to fit the model, called the <em>training set</em>.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="img/validation-split.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<p>We’ll use the <code><a href="https://rsample.tidymodels.org/reference/validation_split.html">validation_split()</a></code> function to allocate 20% of the <code>hotel_other</code> stays to the <em>validation set</em> and 30,000 stays to the <em>training set</em>. This means that our model performance metrics will be computed on a single set of 7,500 hotel stays. This is fairly large, so the amount of data should provide enough precision to be a reliable indicator for how well each model predicts the outcome with a single iteration of resampling.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">234</span><span class="op">)</span></span>
<span><span class="va">val_set</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rsample.tidymodels.org/reference/validation_split.html">validation_split</a></span><span class="op">(</span><span class="va">hotel_other</span>, </span>
<span>                            strata <span class="op">=</span> <span class="va">children</span>, </span>
<span>                            prop <span class="op">=</span> <span class="fl">0.80</span><span class="op">)</span></span>
<span><span class="co">#&gt; Warning: `validation_split()` was deprecated in rsample 1.2.0.</span></span>
<span><span class="co">#&gt; ℹ Please use `initial_validation_split()` instead.</span></span>
<span><span class="va">val_set</span></span>
<span><span class="co">#&gt; # Validation Set Split (0.8/0.2)  using stratification </span></span>
<span><span class="co">#&gt; # A tibble: 1 × 2</span></span>
<span><span class="co">#&gt;   splits               id        </span></span>
<span><span class="co">#&gt;   &lt;list&gt;               &lt;chr&gt;     </span></span>
<span><span class="co">#&gt; 1 &lt;split [30000/7500]&gt; validation</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>This function, like <code><a href="https://rsample.tidymodels.org/reference/initial_split.html">initial_split()</a></code>, has the same <code>strata</code> argument, which uses stratified sampling to create the resample. This means that we’ll have roughly the same proportions of hotel stays with and without children in our new validation and training sets, as compared to the original <code>hotel_other</code> proportions.</p>
</section><section id="first-model" class="level2"><h2 class="anchored" data-anchor-id="first-model">A first model: penalized logistic regression</h2>
<p>Since our outcome variable <code>children</code> is categorical, logistic regression would be a good first model to start. Let’s use a model that can perform feature selection during training. The <a href="https://cran.r-project.org/web/packages/glmnet/index.html">glmnet</a> R package fits a generalized linear model via penalized maximum likelihood. This method of estimating the logistic regression slope parameters uses a <em>penalty</em> on the process so that less relevant predictors are driven towards a value of zero. One of the glmnet penalization methods, called the <a href="https://en.wikipedia.org/wiki/Lasso_(statistics)">lasso method</a>, can actually set the predictor slopes to zero if a large enough penalty is used.</p>
<section id="build-the-model" class="level3"><h3 class="anchored" data-anchor-id="build-the-model">Build the model</h3>
<p>To specify a penalized logistic regression model that uses a feature selection penalty, let’s use the parsnip package with the <a href="../../find/parsnip/">glmnet engine</a>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lr_mod</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/logistic_reg.html">logistic_reg</a></span><span class="op">(</span>penalty <span class="op">=</span> <span class="fu"><a href="https://hardhat.tidymodels.org/reference/tune.html">tune</a></span><span class="op">(</span><span class="op">)</span>, mixture <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/set_engine.html">set_engine</a></span><span class="op">(</span><span class="st">"glmnet"</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>We’ll set the <code>penalty</code> argument to <code><a href="https://hardhat.tidymodels.org/reference/tune.html">tune()</a></code> as a placeholder for now. This is a model hyperparameter that we will <a href="../../start/tuning/">tune</a> to find the best value for making predictions with our data. Setting <code>mixture</code> to a value of one means that the glmnet model will potentially remove irrelevant predictors and choose a simpler model.</p>
</section><section id="create-the-recipe" class="level3"><h3 class="anchored" data-anchor-id="create-the-recipe">Create the recipe</h3>
<p>Let’s create a <a href="../../start/recipes/">recipe</a> to define the preprocessing steps we need to prepare our hotel stays data for this model. It might make sense to create a set of date-based predictors that reflect important components related to the arrival date. We have already introduced a <a href="../../start/recipes/#features">number of useful recipe steps</a> for creating features from dates:</p>
<ul>
<li><p><code><a href="https://recipes.tidymodels.org/reference/step_date.html">step_date()</a></code> creates predictors for the year, month, and day of the week.</p></li>
<li><p><code><a href="https://recipes.tidymodels.org/reference/step_holiday.html">step_holiday()</a></code> generates a set of indicator variables for specific holidays. Although we don’t know where these two hotels are located, we do know that the countries for origin for most stays are based in Europe.</p></li>
<li><p><code><a href="https://recipes.tidymodels.org/reference/step_rm.html">step_rm()</a></code> removes variables; here we’ll use it to remove the original date variable since we no longer want it in the model.</p></li>
</ul>
<p>Additionally, all categorical predictors (e.g., <code>distribution_channel</code>, <code>hotel</code>, …) should be converted to dummy variables, and all numeric predictors need to be centered and scaled.</p>
<ul>
<li><p><code><a href="https://recipes.tidymodels.org/reference/step_dummy.html">step_dummy()</a></code> converts characters or factors (i.e., nominal variables) into one or more numeric binary model terms for the levels of the original data.</p></li>
<li><p><code><a href="https://recipes.tidymodels.org/reference/step_zv.html">step_zv()</a></code> removes indicator variables that only contain a single unique value (e.g. all zeros). This is important because, for penalized models, the predictors should be centered and scaled.</p></li>
<li><p><code><a href="https://recipes.tidymodels.org/reference/step_normalize.html">step_normalize()</a></code> centers and scales numeric variables.</p></li>
</ul>
<p>Putting all these steps together into a recipe for a penalized logistic regression model, we have:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">holidays</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"AllSouls"</span>, <span class="st">"AshWednesday"</span>, <span class="st">"ChristmasEve"</span>, <span class="st">"Easter"</span>, </span>
<span>              <span class="st">"ChristmasDay"</span>, <span class="st">"GoodFriday"</span>, <span class="st">"NewYearsDay"</span>, <span class="st">"PalmSunday"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">lr_recipe</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/recipe.html">recipe</a></span><span class="op">(</span><span class="va">children</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">hotel_other</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_date.html">step_date</a></span><span class="op">(</span><span class="va">arrival_date</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_holiday.html">step_holiday</a></span><span class="op">(</span><span class="va">arrival_date</span>, holidays <span class="op">=</span> <span class="va">holidays</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_rm.html">step_rm</a></span><span class="op">(</span><span class="va">arrival_date</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_dummy.html">step_dummy</a></span><span class="op">(</span><span class="fu"><a href="https://recipes.tidymodels.org/reference/has_role.html">all_nominal_predictors</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_zv.html">step_zv</a></span><span class="op">(</span><span class="fu"><a href="https://recipes.tidymodels.org/reference/has_role.html">all_predictors</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_normalize.html">step_normalize</a></span><span class="op">(</span><span class="fu"><a href="https://recipes.tidymodels.org/reference/has_role.html">all_predictors</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
</section><section id="create-the-workflow" class="level3"><h3 class="anchored" data-anchor-id="create-the-workflow">Create the workflow</h3>
<p>As we introduced in <a href="../../start/recipes/#fit-workflow"><em>Preprocess your data with recipes</em></a>, let’s bundle the model and recipe into a single <code><a href="https://workflows.tidymodels.org/reference/workflow.html">workflow()</a></code> object to make management of the R objects easier:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lr_workflow</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu"><a href="https://workflows.tidymodels.org/reference/workflow.html">workflow</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://workflows.tidymodels.org/reference/add_model.html">add_model</a></span><span class="op">(</span><span class="va">lr_mod</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://workflows.tidymodels.org/reference/add_recipe.html">add_recipe</a></span><span class="op">(</span><span class="va">lr_recipe</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
</section><section id="create-the-grid-for-tuning" class="level3"><h3 class="anchored" data-anchor-id="create-the-grid-for-tuning">Create the grid for tuning</h3>
<p>Before we fit this model, we need to set up a grid of <code>penalty</code> values to tune. In our <a href="../../start/tuning/"><em>Tune model parameters</em></a> article, we used <a href="start/tuning/#tune-grid"><code>dials::grid_regular()</code></a> to create an expanded grid based on a combination of two hyperparameters. Since we have only one hyperparameter to tune here, we can set the grid up manually using a one-column tibble with 30 candidate values:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lr_reg_grid</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>penalty <span class="op">=</span> <span class="fl">10</span><span class="op">^</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="op">-</span><span class="fl">4</span>, <span class="op">-</span><span class="fl">1</span>, length.out <span class="op">=</span> <span class="fl">30</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">lr_reg_grid</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/top_n.html">top_n</a></span><span class="op">(</span><span class="op">-</span><span class="fl">5</span><span class="op">)</span> <span class="co"># lowest penalty values</span></span>
<span><span class="co">#&gt; Selecting by penalty</span></span>
<span><span class="co">#&gt; # A tibble: 5 × 1</span></span>
<span><span class="co">#&gt;    penalty</span></span>
<span><span class="co">#&gt;      &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 0.0001  </span></span>
<span><span class="co">#&gt; 2 0.000127</span></span>
<span><span class="co">#&gt; 3 0.000161</span></span>
<span><span class="co">#&gt; 4 0.000204</span></span>
<span><span class="co">#&gt; 5 0.000259</span></span>
<span><span class="va">lr_reg_grid</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/top_n.html">top_n</a></span><span class="op">(</span><span class="fl">5</span><span class="op">)</span>  <span class="co"># highest penalty values</span></span>
<span><span class="co">#&gt; Selecting by penalty</span></span>
<span><span class="co">#&gt; # A tibble: 5 × 1</span></span>
<span><span class="co">#&gt;   penalty</span></span>
<span><span class="co">#&gt;     &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1  0.0386</span></span>
<span><span class="co">#&gt; 2  0.0489</span></span>
<span><span class="co">#&gt; 3  0.0621</span></span>
<span><span class="co">#&gt; 4  0.0788</span></span>
<span><span class="co">#&gt; 5  0.1</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
</section><section id="train-and-tune-the-model" class="level3"><h3 class="anchored" data-anchor-id="train-and-tune-the-model">Train and tune the model</h3>
<p>Let’s use <code><a href="https://tune.tidymodels.org/reference/tune_grid.html">tune::tune_grid()</a></code> to train these 30 penalized logistic regression models. We’ll also save the validation set predictions (via the call to <code><a href="https://tune.tidymodels.org/reference/control_grid.html">control_grid()</a></code>) so that diagnostic information can be available after the model fit. The area under the ROC curve will be used to quantify how well the model performs across a continuum of event thresholds (recall that the event rate—the proportion of stays including children— is very low for these data).</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lr_res</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">lr_workflow</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tune.tidymodels.org/reference/tune_grid.html">tune_grid</a></span><span class="op">(</span><span class="va">val_set</span>,</span>
<span>            grid <span class="op">=</span> <span class="va">lr_reg_grid</span>,</span>
<span>            control <span class="op">=</span> <span class="fu"><a href="https://tune.tidymodels.org/reference/control_grid.html">control_grid</a></span><span class="op">(</span>save_pred <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            metrics <span class="op">=</span> <span class="fu"><a href="https://yardstick.tidymodels.org/reference/metric_set.html">metric_set</a></span><span class="op">(</span><span class="va">roc_auc</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>It might be easier to visualize the validation set metrics by plotting the area under the ROC curve against the range of penalty values:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lr_plot</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">lr_res</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tune.tidymodels.org/reference/collect_predictions.html">collect_metrics</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">penalty</span>, y <span class="op">=</span> <span class="va">mean</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">"Area under the ROC Curve"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_log10</a></span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/label_number.html">label_number</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">lr_plot</span> </span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="figs/logistic-results-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>This plots shows us that model performance is generally better at the smaller penalty values. This suggests that the majority of the predictors are important to the model. We also see a steep drop in the area under the ROC curve towards the highest penalty values. This happens because a large enough penalty will remove <em>all</em> predictors from the model, and not surprisingly predictive accuracy plummets with no predictors in the model (recall that an ROC AUC value of 0.50 means that the model does no better than chance at predicting the correct class).</p>
<p>Our model performance seems to plateau at the smaller penalty values, so going by the <code>roc_auc</code> metric alone could lead us to multiple options for the “best” value for this hyperparameter:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">top_models</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">lr_res</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tune.tidymodels.org/reference/show_best.html">show_best</a></span><span class="op">(</span>metric <span class="op">=</span> <span class="st">"roc_auc"</span>, n <span class="op">=</span> <span class="fl">15</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">penalty</span><span class="op">)</span> </span>
<span><span class="va">top_models</span></span>
<span><span class="co">#&gt; # A tibble: 15 × 7</span></span>
<span><span class="co">#&gt;     penalty .metric .estimator  mean     n std_err .config         </span></span>
<span><span class="co">#&gt;       &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;           </span></span>
<span><span class="co">#&gt;  1 0.000127 roc_auc binary     0.872     1      NA pre0_mod02_post0</span></span>
<span><span class="co">#&gt;  2 0.000161 roc_auc binary     0.872     1      NA pre0_mod03_post0</span></span>
<span><span class="co">#&gt;  3 0.000204 roc_auc binary     0.873     1      NA pre0_mod04_post0</span></span>
<span><span class="co">#&gt;  4 0.000259 roc_auc binary     0.873     1      NA pre0_mod05_post0</span></span>
<span><span class="co">#&gt;  5 0.000329 roc_auc binary     0.874     1      NA pre0_mod06_post0</span></span>
<span><span class="co">#&gt;  6 0.000418 roc_auc binary     0.874     1      NA pre0_mod07_post0</span></span>
<span><span class="co">#&gt;  7 0.000530 roc_auc binary     0.875     1      NA pre0_mod08_post0</span></span>
<span><span class="co">#&gt;  8 0.000672 roc_auc binary     0.875     1      NA pre0_mod09_post0</span></span>
<span><span class="co">#&gt;  9 0.000853 roc_auc binary     0.876     1      NA pre0_mod10_post0</span></span>
<span><span class="co">#&gt; 10 0.00108  roc_auc binary     0.876     1      NA pre0_mod11_post0</span></span>
<span><span class="co">#&gt; 11 0.00137  roc_auc binary     0.876     1      NA pre0_mod12_post0</span></span>
<span><span class="co">#&gt; 12 0.00174  roc_auc binary     0.876     1      NA pre0_mod13_post0</span></span>
<span><span class="co">#&gt; 13 0.00221  roc_auc binary     0.876     1      NA pre0_mod14_post0</span></span>
<span><span class="co">#&gt; 14 0.00281  roc_auc binary     0.875     1      NA pre0_mod15_post0</span></span>
<span><span class="co">#&gt; 15 0.00356  roc_auc binary     0.873     1      NA pre0_mod16_post0</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>Every candidate model in this tibble likely includes more predictor variables than the model in the row below it. If we used <code><a href="https://tune.tidymodels.org/reference/show_best.html">select_best()</a></code>, it would return candidate model 11 with a penalty value of 0.00137, shown with the dotted line below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="figs/lr-plot-lines-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>However, we may want to choose a penalty value further along the x-axis, closer to where we start to see the decline in model performance. For example, candidate model 12 with a penalty value of 0.00174 has effectively the same performance as the numerically best model, but might eliminate more predictors. This penalty value is marked by the solid line above. In general, fewer irrelevant predictors is better. If performance is about the same, we’d prefer to choose a higher penalty value.</p>
<p>Let’s select this value and visualize the validation set ROC curve:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lr_best</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">lr_res</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tune.tidymodels.org/reference/collect_predictions.html">collect_metrics</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">penalty</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice</a></span><span class="op">(</span><span class="fl">12</span><span class="op">)</span></span>
<span><span class="va">lr_best</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 7</span></span>
<span><span class="co">#&gt;   penalty .metric .estimator  mean     n std_err .config         </span></span>
<span><span class="co">#&gt;     &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;           </span></span>
<span><span class="co">#&gt; 1 0.00137 roc_auc binary     0.876     1      NA pre0_mod12_post0</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lr_auc</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">lr_res</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tune.tidymodels.org/reference/collect_predictions.html">collect_predictions</a></span><span class="op">(</span>parameters <span class="op">=</span> <span class="va">lr_best</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://yardstick.tidymodels.org/reference/roc_curve.html">roc_curve</a></span><span class="op">(</span><span class="va">children</span>, <span class="va">.pred_children</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>model <span class="op">=</span> <span class="st">"Logistic Regression"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="va">lr_auc</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="figs/logistic-roc-curve-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The level of performance generated by this logistic regression model is good, but not groundbreaking. Perhaps the linear nature of the prediction equation is too limiting for this data set. As a next step, we might consider a highly non-linear model generated using a tree-based ensemble method.</p>
</section></section><section id="second-model" class="level2"><h2 class="anchored" data-anchor-id="second-model">A second model: tree-based ensemble</h2>
<p>An effective and low-maintenance modeling technique is a <em>random forest</em>. This model was also used in our <a href="../../start/resampling/"><em>Evaluate your model with resampling</em></a> article. Compared to logistic regression, a random forest model is more flexible. A random forest is an <em>ensemble model</em> typically made up of thousands of decision trees, where each individual tree sees a slightly different version of the training data and learns a sequence of splitting rules to predict new data. Each tree is non-linear, and aggregating across trees makes random forests also non-linear but more robust and stable compared to individual trees. Tree-based models like random forests require very little preprocessing and can effectively handle many types of predictors (sparse, skewed, continuous, categorical, etc.).</p>
<section id="build-the-model-and-improve-training-time" class="level3"><h3 class="anchored" data-anchor-id="build-the-model-and-improve-training-time">Build the model and improve training time</h3>
<p>Although the default hyperparameters for random forests tend to give reasonable results, we’ll plan to tune two hyperparameters that we think could improve performance. Unfortunately, random forest models can be computationally expensive to train and to tune. The computations required for model tuning can usually be easily parallelized to improve training time. The tune package can do <a href="https://tune.tidymodels.org/articles/extras/optimizations.html#parallel-processing">parallel processing</a> for you, and allows users to use multiple cores or separate machines to fit models.</p>
<p>But, here we are using a single validation set, so parallelization isn’t an option using the tune package. For this specific case study, a good alternative is provided by the engine itself. The ranger package offers a built-in way to compute individual random forest models in parallel. To do this, we need to know the the number of cores we have to work with. We can use the parallel package to query the number of cores on your own computer to understand how much parallelization you can do:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">cores</span> <span class="op">&lt;-</span> <span class="fu">parallel</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/r/parallel/detectCores.html">detectCores</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">cores</span></span>
<span><span class="co">#&gt; [1] 14</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>We have 14 cores to work with. We can pass this information to the ranger engine when we set up our parsnip <code><a href="https://parsnip.tidymodels.org/reference/rand_forest.html">rand_forest()</a></code> model. To enable parallel processing, we can pass engine-specific arguments like <code>num.threads</code> to ranger when we set the engine:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">rf_mod</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/rand_forest.html">rand_forest</a></span><span class="op">(</span>mtry <span class="op">=</span> <span class="fu"><a href="https://hardhat.tidymodels.org/reference/tune.html">tune</a></span><span class="op">(</span><span class="op">)</span>, min_n <span class="op">=</span> <span class="fu"><a href="https://hardhat.tidymodels.org/reference/tune.html">tune</a></span><span class="op">(</span><span class="op">)</span>, trees <span class="op">=</span> <span class="fl">1000</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/set_engine.html">set_engine</a></span><span class="op">(</span><span class="st">"ranger"</span>, num.threads <span class="op">=</span> <span class="va">cores</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/set_args.html">set_mode</a></span><span class="op">(</span><span class="st">"classification"</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>This works well in this modeling context, but it bears repeating: if you use any other resampling method, let tune do the parallel processing for you — we typically do not recommend relying on the modeling engine (like we did here) to do this.</p>
<p>In this model, we used <code><a href="https://hardhat.tidymodels.org/reference/tune.html">tune()</a></code> as a placeholder for the <code>mtry</code> and <code>min_n</code> argument values, because these are our two hyperparameters that we will <a href="../../start/tuning/">tune</a>.</p>
</section><section id="create-the-recipe-and-workflow" class="level3"><h3 class="anchored" data-anchor-id="create-the-recipe-and-workflow">Create the recipe and workflow</h3>
<p>Unlike penalized logistic regression models, random forest models do not require <a href="https://bookdown.org/max/FES/categorical-trees.html">dummy</a> or normalized predictor variables. Nevertheless, we want to do some feature engineering again with our <code>arrival_date</code> variable. As before, the date predictor is engineered so that the random forest model does not need to work hard to tease these potential patterns from the data.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">rf_recipe</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/recipe.html">recipe</a></span><span class="op">(</span><span class="va">children</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">hotel_other</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_date.html">step_date</a></span><span class="op">(</span><span class="va">arrival_date</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_holiday.html">step_holiday</a></span><span class="op">(</span><span class="va">arrival_date</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_rm.html">step_rm</a></span><span class="op">(</span><span class="va">arrival_date</span><span class="op">)</span> </span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>Adding this recipe to our parsnip model gives us a new workflow for predicting whether a hotel stay included children and/or babies as guests with a random forest:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">rf_workflow</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu"><a href="https://workflows.tidymodels.org/reference/workflow.html">workflow</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://workflows.tidymodels.org/reference/add_model.html">add_model</a></span><span class="op">(</span><span class="va">rf_mod</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://workflows.tidymodels.org/reference/add_recipe.html">add_recipe</a></span><span class="op">(</span><span class="va">rf_recipe</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
</section><section id="train-and-tune-the-model-1" class="level3"><h3 class="anchored" data-anchor-id="train-and-tune-the-model-1">Train and tune the model</h3>
<p>When we set up our parsnip model, we chose two hyperparameters for tuning:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">rf_mod</span></span>
<span><span class="co">#&gt; Random Forest Model Specification (classification)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Main Arguments:</span></span>
<span><span class="co">#&gt;   mtry = tune()</span></span>
<span><span class="co">#&gt;   trees = 1000</span></span>
<span><span class="co">#&gt;   min_n = tune()</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Engine-Specific Arguments:</span></span>
<span><span class="co">#&gt;   num.threads = cores</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Computational engine: ranger</span></span>
<span></span>
<span><span class="co"># show what will be tuned</span></span>
<span><span class="fu"><a href="https://hardhat.tidymodels.org/reference/hardhat-extract.html">extract_parameter_set_dials</a></span><span class="op">(</span><span class="va">rf_mod</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>The <code>mtry</code> hyperparameter sets the number of predictor variables that each node in the decision tree “sees” and can learn about, so it can range from 1 to the total number of features present; when <code>mtry</code> = all possible features, the model is the same as bagging decision trees. The <code>min_n</code> hyperparameter sets the minimum <code>n</code> to split at any node.</p>
<p>We will use a space-filling design to tune, with 25 candidate models:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">345</span><span class="op">)</span></span>
<span><span class="va">rf_res</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">rf_workflow</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tune.tidymodels.org/reference/tune_grid.html">tune_grid</a></span><span class="op">(</span><span class="va">val_set</span>,</span>
<span>            grid <span class="op">=</span> <span class="fl">25</span>,</span>
<span>            control <span class="op">=</span> <span class="fu"><a href="https://tune.tidymodels.org/reference/control_grid.html">control_grid</a></span><span class="op">(</span>save_pred <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            metrics <span class="op">=</span> <span class="fu"><a href="https://yardstick.tidymodels.org/reference/metric_set.html">metric_set</a></span><span class="op">(</span><span class="va">roc_auc</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; i Creating pre-processing data to finalize 1 unknown parameter: "mtry"</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>The message printed above <em>“Creating pre-processing data to finalize unknown parameter: mtry”</em> is related to the size of the data set. Since <code>mtry</code> depends on the number of predictors in the data set, <code><a href="https://tune.tidymodels.org/reference/tune_grid.html">tune_grid()</a></code> determines the upper bound for <code>mtry</code> once it receives the data.</p>
<p>Here are our top 5 random forest models, out of the 25 candidates:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">rf_res</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tune.tidymodels.org/reference/show_best.html">show_best</a></span><span class="op">(</span>metric <span class="op">=</span> <span class="st">"roc_auc"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 5 × 8</span></span>
<span><span class="co">#&gt;    mtry min_n .metric .estimator  mean     n std_err .config         </span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;           </span></span>
<span><span class="co">#&gt; 1     9     3 roc_auc binary     0.926     1      NA pre0_mod09_post0</span></span>
<span><span class="co">#&gt; 2     8    11 roc_auc binary     0.926     1      NA pre0_mod08_post0</span></span>
<span><span class="co">#&gt; 3     4     5 roc_auc binary     0.924     1      NA pre0_mod04_post0</span></span>
<span><span class="co">#&gt; 4    10    21 roc_auc binary     0.924     1      NA pre0_mod10_post0</span></span>
<span><span class="co">#&gt; 5     5    19 roc_auc binary     0.924     1      NA pre0_mod05_post0</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>Right away, we see that these values for area under the ROC look more promising than our top model using penalized logistic regression, which yielded an ROC AUC of 0.876.</p>
<p>Plotting the results of the tuning process highlights that both <code>mtry</code> (number of predictors at each node) and <code>min_n</code> (minimum number of data points required to keep splitting) should be fairly small to optimize performance. However, the range of the y-axis indicates that the model is very robust to the choice of these parameter values — all but one of the ROC AUC values are greater than 0.90.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="va">rf_res</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="figs/rf-results-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Let’s select the best model according to the ROC AUC metric. Our final tuning parameter values are:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">rf_best</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">rf_res</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tune.tidymodels.org/reference/show_best.html">select_best</a></span><span class="op">(</span>metric <span class="op">=</span> <span class="st">"roc_auc"</span><span class="op">)</span></span>
<span><span class="va">rf_best</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 3</span></span>
<span><span class="co">#&gt;    mtry min_n .config         </span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;int&gt; &lt;chr&gt;           </span></span>
<span><span class="co">#&gt; 1     9     3 pre0_mod09_post0</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>To calculate the data needed to plot the ROC curve, we use <code><a href="https://tune.tidymodels.org/reference/collect_predictions.html">collect_predictions()</a></code>. This is only possible after tuning with <code>control_grid(save_pred = TRUE)</code>. In the output, you can see the two columns that hold our class probabilities for predicting hotel stays including and not including children.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">rf_res</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tune.tidymodels.org/reference/collect_predictions.html">collect_predictions</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 187,500 × 8</span></span>
<span><span class="co">#&gt;    .pred_children .pred_none id         children  .row  mtry min_n .config      </span></span>
<span><span class="co">#&gt;             &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;      &lt;fct&gt;    &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;        </span></span>
<span><span class="co">#&gt;  1         0.0699      0.930 validation none        13     1    24 pre0_mod01_p…</span></span>
<span><span class="co">#&gt;  2         0.0533      0.947 validation none        20     1    24 pre0_mod01_p…</span></span>
<span><span class="co">#&gt;  3         0.0685      0.932 validation children    22     1    24 pre0_mod01_p…</span></span>
<span><span class="co">#&gt;  4         0.0572      0.943 validation none        23     1    24 pre0_mod01_p…</span></span>
<span><span class="co">#&gt;  5         0.0679      0.932 validation none        31     1    24 pre0_mod01_p…</span></span>
<span><span class="co">#&gt;  6         0.0442      0.956 validation none        38     1    24 pre0_mod01_p…</span></span>
<span><span class="co">#&gt;  7         0.0350      0.965 validation none        39     1    24 pre0_mod01_p…</span></span>
<span><span class="co">#&gt;  8         0.0482      0.952 validation none        50     1    24 pre0_mod01_p…</span></span>
<span><span class="co">#&gt;  9         0.0592      0.941 validation none        54     1    24 pre0_mod01_p…</span></span>
<span><span class="co">#&gt; 10         0.0750      0.925 validation children    57     1    24 pre0_mod01_p…</span></span>
<span><span class="co">#&gt; # ℹ 187,490 more rows</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>To filter the predictions for only our best random forest model, we can use the <code>parameters</code> argument and pass it our tibble with the best hyperparameter values from tuning, which we called <code>rf_best</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">rf_auc</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">rf_res</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tune.tidymodels.org/reference/collect_predictions.html">collect_predictions</a></span><span class="op">(</span>parameters <span class="op">=</span> <span class="va">rf_best</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://yardstick.tidymodels.org/reference/roc_curve.html">roc_curve</a></span><span class="op">(</span><span class="va">children</span>, <span class="va">.pred_children</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>model <span class="op">=</span> <span class="st">"Random Forest"</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>Now, we can compare the validation set ROC curves for our top penalized logistic regression model and random forest model:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind_rows.html">bind_rows</a></span><span class="op">(</span><span class="va">rf_auc</span>, <span class="va">lr_auc</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">1</span> <span class="op">-</span> <span class="va">specificity</span>, y <span class="op">=</span> <span class="va">sensitivity</span>, col <span class="op">=</span> <span class="va">model</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_path</a></span><span class="op">(</span>lwd <span class="op">=</span> <span class="fl">1.5</span>, alpha <span class="op">=</span> <span class="fl">0.8</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline</a></span><span class="op">(</span>lty <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_fixed.html">coord_equal</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_viridis.html">scale_color_viridis_d</a></span><span class="op">(</span>option <span class="op">=</span> <span class="st">"plasma"</span>, end <span class="op">=</span> <span class="fl">.6</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="figs/rf-lr-roc-curve-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The random forest is uniformly better across event probability thresholds.</p>
</section></section><section id="last-fit" class="level2"><h2 class="anchored" data-anchor-id="last-fit">The last fit</h2>
<p>Our goal was to predict which hotel stays included children and/or babies. The random forest model clearly performed better than the penalized logistic regression model, and would be our best bet for predicting hotel stays with and without children. After selecting our best model and hyperparameter values, our last step is to fit the final model on all the rows of data not originally held out for testing (both the training and the validation sets combined), and then evaluate the model performance one last time with the held-out test set.</p>
<p>We’ll start by building our parsnip model object again from scratch. We take our best hyperparameter values from our random forest model. When we set the engine, we add a new argument: <code>importance = "impurity"</code>. This will provide <em>variable importance</em> scores for this last model, which gives some insight into which predictors drive model performance.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># the last model</span></span>
<span><span class="va">last_rf_mod</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/rand_forest.html">rand_forest</a></span><span class="op">(</span>mtry <span class="op">=</span> <span class="fl">8</span>, min_n <span class="op">=</span> <span class="fl">7</span>, trees <span class="op">=</span> <span class="fl">1000</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/set_engine.html">set_engine</a></span><span class="op">(</span><span class="st">"ranger"</span>, num.threads <span class="op">=</span> <span class="va">cores</span>, importance <span class="op">=</span> <span class="st">"impurity"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/set_args.html">set_mode</a></span><span class="op">(</span><span class="st">"classification"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># the last workflow</span></span>
<span><span class="va">last_rf_workflow</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">rf_workflow</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://workflows.tidymodels.org/reference/add_model.html">update_model</a></span><span class="op">(</span><span class="va">last_rf_mod</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># the last fit</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">345</span><span class="op">)</span></span>
<span><span class="va">last_rf_fit</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">last_rf_workflow</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tune.tidymodels.org/reference/last_fit.html">last_fit</a></span><span class="op">(</span><span class="va">splits</span><span class="op">)</span></span>
<span></span>
<span><span class="va">last_rf_fit</span></span>
<span><span class="co">#&gt; # Resampling results</span></span>
<span><span class="co">#&gt; # Manual resampling </span></span>
<span><span class="co">#&gt; # A tibble: 1 × 6</span></span>
<span><span class="co">#&gt;   splits                id             .metrics .notes   .predictions .workflow </span></span>
<span><span class="co">#&gt;   &lt;list&gt;                &lt;chr&gt;          &lt;list&gt;   &lt;list&gt;   &lt;list&gt;       &lt;list&gt;    </span></span>
<span><span class="co">#&gt; 1 &lt;split [37500/12500]&gt; train/test sp… &lt;tibble&gt; &lt;tibble&gt; &lt;tibble&gt;     &lt;workflow&gt;</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>This fitted workflow contains <em>everything</em>, including our final metrics based on the test set. So, how did this model do on the test set? Was the validation set a good estimate of future performance?</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">last_rf_fit</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tune.tidymodels.org/reference/collect_predictions.html">collect_metrics</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 3 × 4</span></span>
<span><span class="co">#&gt;   .metric     .estimator .estimate .config        </span></span>
<span><span class="co">#&gt;   &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;          </span></span>
<span><span class="co">#&gt; 1 accuracy    binary        0.946  pre0_mod0_post0</span></span>
<span><span class="co">#&gt; 2 roc_auc     binary        0.923  pre0_mod0_post0</span></span>
<span><span class="co">#&gt; 3 brier_class binary        0.0423 pre0_mod0_post0</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>This ROC AUC value is pretty close to what we saw when we tuned the random forest model with the validation set, which is good news. That means that our estimate of how well our model would perform with new data was not too far off from how well our model actually performed with the unseen test data.</p>
<p>We can access those variable importance scores via the <code>.workflow</code> column. We can <a href="https://tune.tidymodels.org/reference/extract-tune.html">extract out the fit</a> from the workflow object, and then use the vip package to visualize the variable importance scores for the top 20 features:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">last_rf_fit</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://hardhat.tidymodels.org/reference/hardhat-extract.html">extract_fit_parsnip</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">vip</span><span class="op">(</span>num_features <span class="op">=</span> <span class="fl">20</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="figs/rf-importance-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The most important predictors in whether a hotel stay had children or not were the daily cost for the room, the type of room reserved, the time between the creation of the reservation and the arrival date, and the type of room that was ultimately assigned.</p>
<p>Let’s generate our last ROC curve to visualize. Since the event we are predicting is the first level in the <code>children</code> factor (“children”), we provide <code><a href="https://yardstick.tidymodels.org/reference/roc_curve.html">roc_curve()</a></code> with the <a href="https://yardstick.tidymodels.org/reference/roc_curve.html#relevant-level">relevant class probability</a> <code>.pred_children</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">last_rf_fit</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tune.tidymodels.org/reference/collect_predictions.html">collect_predictions</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://yardstick.tidymodels.org/reference/roc_curve.html">roc_curve</a></span><span class="op">(</span><span class="va">children</span>, <span class="va">.pred_children</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="figs/test-set-roc-curve-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Based on these results, the validation set and test set performance statistics are very close, so we would have pretty high confidence that our random forest model with the selected hyperparameters would perform well when predicting new data.</p>
</section><section id="next" class="level2"><h2 class="anchored" data-anchor-id="next">Where to next?</h2>
<p>If you’ve made it to the end of this series of <a href="../../start/"><em>Get Started</em></a> articles, we hope you feel ready to learn more! You now know the core tidymodels packages and how they fit together. After you are comfortable with the basics we introduced in this series, you can <a href="../../learn/">learn how to go farther</a> with tidymodels in your modeling and machine learning projects.</p>
<p>Here are some more ideas for where to go next:</p>
<ul>
<li><p>Study up on statistics and modeling with our comprehensive <a href="../../books/">books</a>.</p></li>
<li><p>Dig deeper into the <a href="../../packages/">package documentation sites</a> to find functions that meet your modeling needs. Use the <a href="../../find/">searchable tables</a> to explore what is possible.</p></li>
<li><p>Keep up with the latest about tidymodels packages at the <a href="https://www.tidyverse.org/tags/tidymodels/">tidyverse blog</a>.</p></li>
<li><p>Find ways to ask for <a href="../../help/">help</a> and <a href="../../contribute">contribute to tidymodels</a> to help others.</p></li>
</ul>
<p>###</p>
<center>
Happy modeling!
</center>
</section><section id="session-info" class="level2"><h2 class="anchored" data-anchor-id="session-info">Session information</h2>
<div class="cell" data-layout-align="center">
<pre><code>#&gt; ─ Session info ─────────────────────────────────────────────────────
#&gt;  version  R version 4.5.2 (2025-10-31)
#&gt;  language (EN)
#&gt;  date     2026-04-22
#&gt;  pandoc   3.8.3
#&gt;  quarto   1.9.35
#&gt; 
#&gt; ─ Packages ─────────────────────────────────────────────────────────
#&gt;  package      version date (UTC)
#&gt;  broom        1.0.12  2026-01-27
#&gt;  dials        1.4.3   2026-04-11
#&gt;  dplyr        1.2.1   2026-04-03
#&gt;  ggplot2      4.0.3   2026-04-22
#&gt;  glmnet       4.1-10  2025-07-17
#&gt;  here         1.0.2   2025-09-15
#&gt;  infer        1.1.0   2025-12-18
#&gt;  parsnip      1.5.0   2026-04-09
#&gt;  purrr        1.2.2   2026-04-10
#&gt;  ranger       0.18.0  2026-01-16
#&gt;  readr        2.2.0   2026-02-19
#&gt;  recipes      1.3.2   2026-04-02
#&gt;  rlang        1.2.0   2026-04-06
#&gt;  rsample      1.3.2   2026-01-30
#&gt;  scales       1.4.0   2025-04-24
#&gt;  tibble       3.3.1   2026-01-11
#&gt;  tidymodels   1.4.1   2025-09-08
#&gt;  tune         2.1.0   2026-04-17
#&gt;  vip          0.4.5   2025-12-12
#&gt;  workflows    1.3.0   2025-08-27
#&gt;  yardstick    1.4.0   2026-04-07
#&gt; 
#&gt; ────────────────────────────────────────────────────────────────────</code></pre>
</div>


</section></main><!-- /main --><!-- plausible --><script async="" defer data-domain="tidymodels.org,all.tidymodels.org" src="https://plausible.io/js/plausible.js"></script><script>
document.querySelector('.toc-actions').remove();
</script><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/www\.tidymodels\.org");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Proudly supported by <a href="https://posit.co"><img src="https://posit.co/wp-content/themes/Posit/assets/images/posit-logo-2024.svg" class="img-fluid" alt="Posit" width="65"></a></p>
</div>   
    <div class="nav-footer-center">
       
    <div class="toc-actions d-sm-block d-md-none"><ul>
<li><a href="https://github.com/tidymodels/tidymodels.org/edit/main/start/case-study/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li>
<li><a href="https://github.com/tidymodels/tidymodels.org/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li>
</ul></div>
</div>
    <div class="nav-footer-right">
<p><a onclick="window.scrollTo({ top: 0, behavior: 'smooth' }); return false;" role="button"> <i class="fa-solid fa-chevron-up" aria-label="chevron-up"></i> </a></p>
</div>
  </div>
</footer>
</body>
</html>
