---
subtitle: Recipes
title: Search recipe steps
weight: 3
description: | 
  Find recipe steps in the tidymodels framework to help you prep your data for modeling.
---

```{r}
#| label: startup
#| include: false
#| cache: false
knitr::opts_chunk$set(
  message = FALSE,
  digits = 3,
  collapse = TRUE,
  comment = "#>"
  )
options(digits = 3)

library(DT)
library(tibble)
library(dplyr)
source(here::here("pkgdown_urls.R"))
```

```{r}
#| label: get-pkgs
#| include: false
pkgs <- 
  tibble(
    pkg = c("recipes", "embed", "textrecipes", "themis"), 
    base_url = "https://tidymodels.github.io/"
  ) %>% 
  dplyr::bind_rows(
    tibble(
      pkg = "timetk", 
      base_url = "https://business-science.github.io/"
    )
  ) 
  # MachineShop has step functions but pkgdown reference pages 
  # redirect to https://www.rdocumentation.org/
  # dplyr::bind_rows(
  #   tibble(
  #     pkg = "MachineShop", 
  #     base_url = "https://brian-j-smith.github.io/"
  #   ) 
  # ) 
  # healthcareai has a number of step functions but they are not documented
  # on their pkgdown site
  # dplyr::bind_rows(
  #   tibble(
  #     pkg = "healthcareai", 
  #     base_url = "https://docs.healthcare.ai/"
  #   ) 
  # )
  # customsteps package has no pkgdown site
```

To learn about the recipes package, see [*Get Started: Preprocess your data with recipes*](/start/recipes/). The table below allows you to search for recipe steps across tidymodels packages.

```{r}
#| label: table-compute
#| include: false

pkg_urls <- get_pkgdown_urls(pkgs, fltr = "(^check_)|(^step_)") %>% 
  select(title, topic, package) %>% 
  mutate(package = as.factor(package))

#TODO sort by type then name

```

```{r}
#| label: table-display
#| echo: false
#| results: asis
DT::datatable(
  pkg_urls,
  rownames = FALSE,
  class = 'cell-border stripe',
  escape = FALSE,
  filter = "top",
  options = list(pageLength = 5)
)
```
