<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="With information on a diabetes patient’s stay at a hospital like demographics, diagnostic results, payment, and medications, a hospital can train a machine learning model to predict reasonably well whether a patient will be readmitted within 30 days. What harms to patients could result from using such a model, though?">
<title>Fair prediction of hospital readmission: a machine learning fairness case study – tidymodels</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>
<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script><script src="../../../site_libs/clipboard/clipboard.min.js"></script><script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script><script src="../../../site_libs/quarto-search/fuse.min.js"></script><script src="../../../site_libs/quarto-search/quarto-search.js"></script><meta name="quarto:offset" content="../../../">
<link href="../../../favicon.ico" rel="icon">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script><script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script><script src="../../../site_libs/quarto-html/popper.min.js"></script><script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script><script src="../../../site_libs/quarto-html/anchor.min.js"></script><link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-a9c94084e156453ce75ecc8ff7b2041c.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script><link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-8348b2d5c2bb4a73246cdd5819180553.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
</head>
<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">tidymodels</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item">
    <a class="nav-link" href="../../../packages/index.html"> 
<span class="menu-text">Packages</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../start/index.html"> 
<span class="menu-text">Get Started</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../learn/index.html"> 
<span class="menu-text">Learn</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../help/index.html"> 
<span class="menu-text">Help</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../contribute/index.html"> 
<span class="menu-text">Contribute</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about/index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../find/index.html"> 
<span class="menu-text">Find</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/tidymodels/"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
<li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#exploratory-analysis" id="toc-exploratory-analysis" class="nav-link" data-scroll-target="#exploratory-analysis">Exploratory Analysis</a></li>
  <li><a href="#resampling-data" id="toc-resampling-data" class="nav-link" data-scroll-target="#resampling-data">Resampling Data</a></li>
  <li><a href="#training-and-evaluating-models" id="toc-training-and-evaluating-models" class="nav-link" data-scroll-target="#training-and-evaluating-models">Training and Evaluating Models</a></li>
  <li><a href="#model-selection" id="toc-model-selection" class="nav-link" data-scroll-target="#model-selection">Model Selection</a></li>
  <li><a href="#session-info" id="toc-session-info" class="nav-link" data-scroll-target="#session-info">Session information</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse">
<li><a href="https://github.com/tidymodels/tidymodels.org/edit/main/learn/work/fairness-readmission/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li>
<li><a href="https://github.com/tidymodels/tidymodels.org/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li>
</ul></div></nav>
</div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Fair prediction of hospital readmission: a machine learning fairness case study</h1>
  <div class="quarto-categories">
    <div class="quarto-category">yardstick</div>
    <div class="quarto-category">fairness</div>
    <div class="quarto-category">tuning</div>
    <div class="quarto-category">classification</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>With information on a diabetes patient’s stay at a hospital like demographics, diagnostic results, payment, and medications, a hospital can train a machine learning model to predict reasonably well whether a patient will be readmitted within 30 days. What harms to patients could result from using such a model, though?</p>
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><hr>
<p>In 2019, <span class="citation" data-cites="obermeyer2019">Obermeyer et al. (<a href="#ref-obermeyer2019" role="doc-biblioref">2019</a>)</span> published an analysis of predictions from a machine learning model that health care providers use to allocate resources. The model’s outputs are used to recommend a patient for <em>high-risk care management</em> programs:</p>
<blockquote class="blockquote">
<p>These programs seek to improve the care of patients with complex health needs by providing additional resources, including greater attention from trained providers, to help ensure that care is well coordinated. Most health systems use these programs as the cornerstone of population health management efforts, and they are widely considered effective at improving outcomes and satisfaction while reducing costs. […] Because the programs are themselves expensive—with costs going toward teams of dedicated nurses, extra primary care appointment slots, and other scarce resources—<strong>health systems rely extensively on algorithms to identify patients who will benefit the most.</strong></p>
</blockquote>
<p>They argue in their analysis that the model in question exhibits substantial racial bias, where “Black patients assigned the same level of risk by the algorithm are sicker than White patients.” In practice, this resulted in the reduction of “the number of Black patients identified for extra care by more than half.”</p>
<p>This article will demonstrate a fairness-oriented workflow for training a machine learning model to identify high-risk patients. Throughout the model development process, we’ll consider the social impacts that different modeling decisions may have when such a model is deployed in context.</p>
<section id="setup" class="level2"><h2 class="anchored" data-anchor-id="setup">Setup</h2>
<p>The data we’ll use in this analysis is a publicly available database containing information on 71,515 hospital stays from diabetes patients. The data comes from a study by <span class="citation" data-cites="strack2014"><span class="nocase">Strack et al.</span> (<a href="#ref-strack2014" role="doc-biblioref">2014</a>)</span>, where the authors model the effectiveness of a particular lab test in predicting readmission. A version of that data is available in the <a href="https://simonpcouch.github.io/readmission/">readmission R package</a>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">readmission</span><span class="op">)</span></span>
<span></span>
<span><span class="va">readmission</span></span>
<span><span class="co">#&gt; # A tibble: 71,515 × 12</span></span>
<span><span class="co">#&gt;    readmitted race   sex   age   admission_source blood_glucose insurer duration</span></span>
<span><span class="co">#&gt;    &lt;fct&gt;      &lt;fct&gt;  &lt;fct&gt; &lt;fct&gt; &lt;fct&gt;            &lt;fct&gt;         &lt;fct&gt;      &lt;dbl&gt;</span></span>
<span><span class="co">#&gt;  1 Yes        Afric… Male  [60-… Referral         &lt;NA&gt;          &lt;NA&gt;           7</span></span>
<span><span class="co">#&gt;  2 No         Cauca… Fema… [50-… Emergency        Normal        Private        4</span></span>
<span><span class="co">#&gt;  3 Yes        Cauca… Fema… [70-… Referral         &lt;NA&gt;          Medica…        5</span></span>
<span><span class="co">#&gt;  4 No         Cauca… Fema… [80-… Referral         &lt;NA&gt;          Private        5</span></span>
<span><span class="co">#&gt;  5 No         Cauca… Fema… [70-… Referral         &lt;NA&gt;          &lt;NA&gt;           4</span></span>
<span><span class="co">#&gt;  6 No         Cauca… Male  [50-… Emergency        Very High     &lt;NA&gt;           2</span></span>
<span><span class="co">#&gt;  7 Yes        Afric… Fema… [70-… Referral         &lt;NA&gt;          Private        3</span></span>
<span><span class="co">#&gt;  8 No         Cauca… Fema… [20-… Emergency        &lt;NA&gt;          &lt;NA&gt;           1</span></span>
<span><span class="co">#&gt;  9 No         Cauca… Male  [60-… Other            &lt;NA&gt;          &lt;NA&gt;          12</span></span>
<span><span class="co">#&gt; 10 No         Cauca… Fema… [80-… Referral         &lt;NA&gt;          Medica…        1</span></span>
<span><span class="co">#&gt; # ℹ 71,505 more rows</span></span>
<span><span class="co">#&gt; # ℹ 4 more variables: n_previous_visits &lt;dbl&gt;, n_diagnoses &lt;dbl&gt;,</span></span>
<span><span class="co">#&gt; #   n_procedures &lt;dbl&gt;, n_medications &lt;dbl&gt;</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>The first variable in this data, <code>readmitted</code>, gives whether the patient was readmitted within 30 days of discharge. We’ll use this variable as a proxy for “unmet need for additional care,” in that readmission within one month indicates that the patient may have benefited from additional attention during their hospital stay; if a machine learning model consistently identifies lesser need (via prediction of non-readmission) in one subgroup than another, the subgroup allocated lesser need will go without care they’d benefit from. We’d like to train a model that is both fair with regard to how it treats <code>race</code> groups and is as performant as possible. The tidymodels framework provides the tools needed to identify such disparities.</p>
<p>Loading needed packages:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidymodels.tidymodels.org">tidymodels</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://baguette.tidymodels.org">baguette</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://desirability2.tidymodels.org">desirability2</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggobi.github.io/ggally/">GGally</a></span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
</section><section id="exploratory-analysis" class="level2"><h2 class="anchored" data-anchor-id="exploratory-analysis">Exploratory Analysis</h2>
<p>Let’s start off our analysis with some explanatory summarization and plotting. First, taking a look at our outcome variable:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">readmission</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">readmitted</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 2</span></span>
<span><span class="co">#&gt;   readmitted     n</span></span>
<span><span class="co">#&gt;   &lt;fct&gt;      &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1 Yes         6293</span></span>
<span><span class="co">#&gt; 2 No         65222</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>8.8% of patients were readmitted within 30 days after being discharged from the hospital. This is an example of a modeling problem with a <em>class imbalance</em>, where one value of the outcome variable is much more common than another. Now, taking a look at the counts of those in each protected class:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">readmission</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">race</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 6 × 2</span></span>
<span><span class="co">#&gt;   race                 n</span></span>
<span><span class="co">#&gt;   &lt;fct&gt;            &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1 African American 12887</span></span>
<span><span class="co">#&gt; 2 Asian              497</span></span>
<span><span class="co">#&gt; 3 Caucasian        53491</span></span>
<span><span class="co">#&gt; 4 Hispanic          1517</span></span>
<span><span class="co">#&gt; 5 Other             1177</span></span>
<span><span class="co">#&gt; 6 Unknown           1946</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We’ll refer to the <code>race</code> groups in this data by their actual value (e.g. <code>"Caucasian"</code> rather than Caucasian) so as to not take for granted the choices that the dataset authors made in choosing these categorizations. Racial categorizations are not stable across time and place—as you read on, consider how a change in the categories used in data collection might affect this analysis <span class="citation" data-cites="omi1994">(<a href="#ref-omi1994" role="doc-biblioref">Omi and Winant 1994</a>)</span>.</p>
</div>
</div>
<p>A vast majority of patients are labeled <code>"Caucasian"</code> (74.8%) or <code>"African American"</code> (18%). The counts for the remaining racial categorizations are quite a bit smaller, and when we split the data up into resamples, those counts will reduce even further. As a result, the variability associated with the estimates <code>"Asian"</code>, <code>"Hispanic"</code>, <code>"Other"</code>, and <code>"Unknown"</code> will be larger than those for <code>"African American"</code> and <code>"Causasian"</code>. As an example:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">readmission</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="co"># randomly split into groups</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">.</span>, group <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">10</span>, <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">.</span><span class="op">)</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">race</span>, <span class="va">group</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="co"># compute proportion readmitted by race + random `group`ing</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>prop <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">readmitted</span> <span class="op">==</span> <span class="st">"Yes"</span><span class="op">)</span>, n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="co"># compute variation in the proportion by race.</span></span>
<span>  <span class="co"># note that, by default, the output from above is grouped by race only.</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">prop</span><span class="op">)</span>, sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">prop</span><span class="op">)</span>, n <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 6 × 4</span></span>
<span><span class="co">#&gt;   race               mean      sd     n</span></span>
<span><span class="co">#&gt;   &lt;fct&gt;             &lt;dbl&gt;   &lt;dbl&gt; &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1 African American 0.0849 0.00713 12887</span></span>
<span><span class="co">#&gt; 2 Asian            0.0825 0.0295    497</span></span>
<span><span class="co">#&gt; 3 Caucasian        0.0900 0.00369 53491</span></span>
<span><span class="co">#&gt; 4 Hispanic         0.0805 0.0285   1517</span></span>
<span><span class="co">#&gt; 5 Other            0.0680 0.0265   1177</span></span>
<span><span class="co">#&gt; 6 Unknown          0.0720 0.0178   1946</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>The standard deviations <code>sd</code> are much larger for groups with a smaller number of observations <code>n</code>, even if the average proportions <code>mean</code> are similar. This variation will affect our analysis downstream in that fairness metrics measure variation across groups; the noise associated with proportions calculated for <code>race</code> groups with fewer values may overwhelm the signal associated with actual disparities in care for those groups.</p>
<p>We have several options when considering how to address this:</p>
<ul>
<li>
<strong>Remove rows arising from infrequent classes.</strong> In this example, this would mean removing all rows with <code>race</code> values other than <code>"Caucasian"</code> or <code>"African American"</code>. This is the approach taken by other public analyses of these data, including the original study that this data arose from. An analysis resulting from this approach would ignore any disparities in care for <code>race</code> groups other than <code>"Caucasian"</code> or <code>"African American"</code>.</li>
<li>
<strong>Construct custom fairness metrics that address the increased variability associated with smaller counts.</strong> We could scale the variability of the estimates for each <code>race</code> group before calculating fairness metrics.</li>
<li>
<strong>Bin the values for infrequent classes.</strong> This would entail collapsing values of <code>race</code> other than <code>"Caucasian"</code> and <code>"African American"</code> into one factor level. This approach is somewhat of a hybrid of the two approaches above; we lose some granularity in information regarding care for <code>race</code> groups other than <code>"Caucasian"</code> and <code>"African American"</code>, but reduce the variability associated with the estimates for those groups in the process.</li>
</ul>
<p>For this analysis, we’ll go with the last option.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>While we won’t construct custom fairness metrics in this example, you can do so using the <code><a href="https://yardstick.tidymodels.org/reference/new_groupwise_metric.html">new_groupwise_metric()</a></code> function in yardstick.</p>
</div>
</div>
<p>Recoding that data column:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">readmission_collapsed</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">readmission</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    race <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case-and-replace-when.html">case_when</a></span><span class="op">(</span></span>
<span>      <span class="op">!</span><span class="op">(</span><span class="va">race</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Caucasian"</span>, <span class="st">"African American"</span><span class="op">)</span><span class="op">)</span> <span class="op">~</span> <span class="st">"Other"</span>,</span>
<span>      .default <span class="op">=</span> <span class="va">race</span></span>
<span>    <span class="op">)</span>,</span>
<span>    race <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">race</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">readmission_collapsed</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">race</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 3 × 2</span></span>
<span><span class="co">#&gt;   race                 n</span></span>
<span><span class="co">#&gt;   &lt;fct&gt;            &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1 African American 12887</span></span>
<span><span class="co">#&gt; 2 Caucasian        53491</span></span>
<span><span class="co">#&gt; 3 Other             5137</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>Plotting distributions of remaining predictors:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">readmission_collapsed</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">age</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_grid.html">facet_grid</a></span><span class="op">(</span>rows <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/vars.html">vars</a></span><span class="op">(</span><span class="va">admission_source</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="figs/plot-age-by-source-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Most patients in this data are in their 60s and 70s. Emergencies account for most admissions in this data, though many others are from referrals or other sources.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">readmission_collapsed</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">insurer</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="figs/plot-insurer-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>While payment information on most patients is missing, most patients in this data are covered under Medicare.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The payment method is one way in which societal unfairness may be reflected in the source data besides the variables on protected groups themselves. Medicaid coverage is only available to people below a certain income, and many self-pay patients do not have medical insurance because they cannot afford it. Relatedly, poverty rates differ drastically among racial groups in the U.S.</p>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">readmission_collapsed</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with</a></span><span class="op">(</span><span class="st">"n_"</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">value</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/vars.html">vars</a></span><span class="op">(</span><span class="va">name</span><span class="op">)</span>, scales <span class="op">=</span> <span class="st">"free_x"</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="figs/plot-n-variables-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For many patients, this was their first inpatient visit to this hospital system. During their stay, many patients receive 10-20 medications and experience several procedures.</p>
<p>With a sense for the distributions of variables in this dataset, we can move on to splitting data up for modeling.</p>
</section><section id="resampling-data" class="level2"><h2 class="anchored" data-anchor-id="resampling-data">Resampling Data</h2>
<p>First, splitting data into training and testing:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">readmission_splits</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rsample.tidymodels.org/reference/initial_split.html">initial_split</a></span><span class="op">(</span><span class="va">readmission_collapsed</span>, strata <span class="op">=</span> <span class="va">readmitted</span><span class="op">)</span></span>
<span><span class="va">readmission_train</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rsample.tidymodels.org/reference/initial_split.html">training</a></span><span class="op">(</span><span class="va">readmission_splits</span><span class="op">)</span></span>
<span><span class="va">readmission_test</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rsample.tidymodels.org/reference/initial_split.html">testing</a></span><span class="op">(</span><span class="va">readmission_splits</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We’ve set <code>strata = readmitted</code> here to stratify our sample by the outcome variable in order to address the class imbalance. To learn more about class imbalances and stratification, see the <a href="https://www.tmwr.org/splitting#splitting-methods">“Common Methods for Splitting Data”</a> chapter of <a href="https://www.tmwr.org/"><em>Tidy Modeling with R</em></a> <span class="citation" data-cites="kuhn2022">(<a href="#ref-kuhn2022" role="doc-biblioref">Kuhn and Silge 2022</a>)</span>.</p>
</div>
</div>
<p>We’ll set the 17,879-row <code>readmission_test</code> test set to the side for the remainder of the analysis until we compute a final estimate of our performance on the chosen model. Splitting the 53,636 rows of the training data into 10 resamples:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">readmission_folds</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rsample.tidymodels.org/reference/vfold_cv.html">vfold_cv</a></span><span class="op">(</span><span class="va">readmission_train</span>, strata <span class="op">=</span> <span class="va">readmitted</span><span class="op">)</span></span>
<span></span>
<span><span class="va">readmission_folds</span></span>
<span><span class="co">#&gt; #  10-fold cross-validation using stratification </span></span>
<span><span class="co">#&gt; # A tibble: 10 × 2</span></span>
<span><span class="co">#&gt;    splits               id    </span></span>
<span><span class="co">#&gt;    &lt;list&gt;               &lt;chr&gt; </span></span>
<span><span class="co">#&gt;  1 &lt;split [48272/5364]&gt; Fold01</span></span>
<span><span class="co">#&gt;  2 &lt;split [48272/5364]&gt; Fold02</span></span>
<span><span class="co">#&gt;  3 &lt;split [48272/5364]&gt; Fold03</span></span>
<span><span class="co">#&gt;  4 &lt;split [48272/5364]&gt; Fold04</span></span>
<span><span class="co">#&gt;  5 &lt;split [48272/5364]&gt; Fold05</span></span>
<span><span class="co">#&gt;  6 &lt;split [48272/5364]&gt; Fold06</span></span>
<span><span class="co">#&gt;  7 &lt;split [48273/5363]&gt; Fold07</span></span>
<span><span class="co">#&gt;  8 &lt;split [48273/5363]&gt; Fold08</span></span>
<span><span class="co">#&gt;  9 &lt;split [48273/5363]&gt; Fold09</span></span>
<span><span class="co">#&gt; 10 &lt;split [48273/5363]&gt; Fold10</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>Each split contains an analysis and assessment set: one for model fitting and the other for evaluation. Averaging performance estimates across resamples will give us a sense for how well the model performs on data it hasn’t yet seen.</p>
</section><section id="training-and-evaluating-models" class="level2"><h2 class="anchored" data-anchor-id="training-and-evaluating-models">Training and Evaluating Models</h2>
<p>We’ll define a diverse set of models and pre-processing strategies and then evaluate them against our resamples.</p>
<section id="model-workflows" class="level3"><h3 class="anchored" data-anchor-id="model-workflows">Model Workflows</h3>
<p>We’ll first define a basic recipe that first sets a factor level for missing values and then centers and scales numeric data:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">recipe_basic</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/recipe.html">recipe</a></span><span class="op">(</span><span class="va">readmitted</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">readmission</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_unknown.html">step_unknown</a></span><span class="op">(</span><span class="fu"><a href="https://recipes.tidymodels.org/reference/has_role.html">all_nominal_predictors</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_YeoJohnson.html">step_YeoJohnson</a></span><span class="op">(</span><span class="fu"><a href="https://recipes.tidymodels.org/reference/has_role.html">all_numeric_predictors</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_normalize.html">step_normalize</a></span><span class="op">(</span><span class="fu"><a href="https://recipes.tidymodels.org/reference/has_role.html">all_numeric_predictors</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_dummy.html">step_dummy</a></span><span class="op">(</span><span class="fu"><a href="https://recipes.tidymodels.org/reference/has_role.html">all_nominal_predictors</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>The other preprocessor that we’ll try encodes the age as a numeric variable rather than the bins as in the source data:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># e.g. "[10-20]" -&gt; 15</span></span>
<span><span class="va">age_bin_to_midpoint</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">age_bin</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="co"># ensure factors are treated as their label</span></span>
<span>  <span class="va">age</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="va">age_bin</span><span class="op">)</span> </span>
<span>  <span class="co"># take the second character, e.g. "[10-20]" -&gt; "1"</span></span>
<span>  <span class="va">age</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/substr.html">substr</a></span><span class="op">(</span><span class="va">age</span>, <span class="fl">2</span>, <span class="fl">2</span><span class="op">)</span></span>
<span>  <span class="co"># convert to numeric, e.g. "1" -&gt; 1</span></span>
<span>  <span class="va">age</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">age</span><span class="op">)</span></span>
<span>  <span class="co"># scale to bin's midpoint, e.g. 1 -&gt; 10 + 5 -&gt; 15</span></span>
<span>  <span class="va">age</span> <span class="op">*</span> <span class="fl">10</span> <span class="op">+</span> <span class="fl">5</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="va">recipe_age</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/recipe.html">recipe</a></span><span class="op">(</span><span class="va">readmitted</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">readmission</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_mutate.html">step_mutate</a></span><span class="op">(</span>age_num <span class="op">=</span> <span class="fu">age_bin_to_midpoint</span><span class="op">(</span><span class="va">age</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_rm.html">step_rm</a></span><span class="op">(</span><span class="va">age</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_unknown.html">step_unknown</a></span><span class="op">(</span><span class="fu"><a href="https://recipes.tidymodels.org/reference/has_role.html">all_nominal_predictors</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_YeoJohnson.html">step_YeoJohnson</a></span><span class="op">(</span><span class="fu"><a href="https://recipes.tidymodels.org/reference/has_role.html">all_numeric_predictors</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_normalize.html">step_normalize</a></span><span class="op">(</span><span class="fu"><a href="https://recipes.tidymodels.org/reference/has_role.html">all_numeric_predictors</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_dummy.html">step_dummy</a></span><span class="op">(</span><span class="fu"><a href="https://recipes.tidymodels.org/reference/has_role.html">all_nominal_predictors</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>Both of these preprocessors will be combined with one of three models. Logistic regressions, XGBoost, and bagged neural networks make a diverse set of assumptions about the underlying data generating process. Defining model specifications for each:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">spec_lr</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/logistic_reg.html">logistic_reg</a></span><span class="op">(</span><span class="st">"classification"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">spec_bt</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/boost_tree.html">boost_tree</a></span><span class="op">(</span><span class="st">"classification"</span>, mtry <span class="op">=</span> <span class="fu"><a href="https://hardhat.tidymodels.org/reference/tune.html">tune</a></span><span class="op">(</span><span class="op">)</span>, learn_rate <span class="op">=</span> <span class="fu"><a href="https://hardhat.tidymodels.org/reference/tune.html">tune</a></span><span class="op">(</span><span class="op">)</span>, trees <span class="op">=</span> <span class="fl">500</span><span class="op">)</span></span>
<span></span>
<span><span class="va">spec_nn</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/bag_mlp.html">bag_mlp</a></span><span class="op">(</span><span class="st">"classification"</span>, hidden_units <span class="op">=</span> <span class="fu"><a href="https://hardhat.tidymodels.org/reference/tune.html">tune</a></span><span class="op">(</span><span class="op">)</span>, penalty <span class="op">=</span> <span class="fu"><a href="https://hardhat.tidymodels.org/reference/tune.html">tune</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>We now combine each unique combination of recipe and preprocessor in a workflow set:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">wflow_set</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu"><a href="https://workflowsets.tidymodels.org/reference/workflow_set.html">workflow_set</a></span><span class="op">(</span></span>
<span>    preproc <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>basic <span class="op">=</span> <span class="va">recipe_basic</span>, age <span class="op">=</span> <span class="va">recipe_age</span><span class="op">)</span>,</span>
<span>    models <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>lr <span class="op">=</span> <span class="va">spec_lr</span>, bt <span class="op">=</span> <span class="va">spec_bt</span>, nn <span class="op">=</span> <span class="va">spec_nn</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">wflow_set</span></span>
<span><span class="co">#&gt; # A workflow set/tibble: 6 × 4</span></span>
<span><span class="co">#&gt;   wflow_id info             option    result    </span></span>
<span><span class="co">#&gt;   &lt;chr&gt;    &lt;list&gt;           &lt;list&gt;    &lt;list&gt;    </span></span>
<span><span class="co">#&gt; 1 basic_lr &lt;tibble [1 × 4]&gt; &lt;opts[0]&gt; &lt;list [0]&gt;</span></span>
<span><span class="co">#&gt; 2 basic_bt &lt;tibble [1 × 4]&gt; &lt;opts[0]&gt; &lt;list [0]&gt;</span></span>
<span><span class="co">#&gt; 3 basic_nn &lt;tibble [1 × 4]&gt; &lt;opts[0]&gt; &lt;list [0]&gt;</span></span>
<span><span class="co">#&gt; 4 age_lr   &lt;tibble [1 × 4]&gt; &lt;opts[0]&gt; &lt;list [0]&gt;</span></span>
<span><span class="co">#&gt; 5 age_bt   &lt;tibble [1 × 4]&gt; &lt;opts[0]&gt; &lt;list [0]&gt;</span></span>
<span><span class="co">#&gt; 6 age_nn   &lt;tibble [1 × 4]&gt; &lt;opts[0]&gt; &lt;list [0]&gt;</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>Each workflow in the workflow set is now ready to be evaluated. We now need to decide how to best evaluate these modeling workflows, though.</p>
</section><section id="metrics" class="level3"><h3 class="anchored" data-anchor-id="metrics">Metrics</h3>
<p>The metrics with which we choose to evaluate our models are the core of our fairness analysis. In addition to the default metrics for classification in tune, <code><a href="https://yardstick.tidymodels.org/reference/accuracy.html">accuracy()</a></code> and <code><a href="https://yardstick.tidymodels.org/reference/roc_auc.html">roc_auc()</a></code>, we’ll compute a set of fairness metrics: <code><a href="https://yardstick.tidymodels.org/reference/equal_opportunity.html">equal_opportunity()</a></code>, <code><a href="https://yardstick.tidymodels.org/reference/equalized_odds.html">equalized_odds()</a></code>, and <code><a href="https://yardstick.tidymodels.org/reference/demographic_parity.html">demographic_parity()</a></code>.</p>
<ul>
<li><p><code><a href="https://yardstick.tidymodels.org/reference/equal_opportunity.html">equal_opportunity()</a></code>: Equal opportunity is satisfied when a model’s predictions have the same true positive and false negative rates across protected groups. In this example, a model satisfies equal opportunity if it correctly predicts readmission and incorrectly predicts non-readmission at the same rate across <code>race</code> groups. In this case, the metric represents the interests of the patient; a patient would like to be just as likely to receive additional care resources as another if they are of equal need, and no more likely to go without unneeded care than another. Since this metric does not consider false positives, it notably does not penalize disparately providing additional care resources to a patient who may not need them.</p></li>
<li><p><code><a href="https://yardstick.tidymodels.org/reference/equalized_odds.html">equalized_odds()</a></code>: Equalized odds is satisfied when a model’s predictions have the same false positive, true positive, false negative, and true negative rates across protected groups. This definition is a special case of the one above, where there’s additionally a constraint placed on the false positive and true negative rates. In this example, a model satisfies equalized odds if it correctly predicts both readmission and non-readmission <em>and</em> incorrectly predicts readmission and non-readmission at the same rate across <code>race</code> groups. Similar to equal opportunity, the stakeholders for the metric in this case can be generally understood to be those who are subject to the model’s predictions, except that this metric also aims to prevent disparately 1) providing additional care resources to those who may not need them and 2) identifying patients who do <em>not</em> need additional care resources correctly.</p></li>
<li><p><code><a href="https://yardstick.tidymodels.org/reference/demographic_parity.html">demographic_parity()</a></code>: Demographic parity is satisfied when a model’s predictions have the same predicted positive rate across groups. In this example, a model satisfies demographic parity if it predicts readmission at the same rate across <code>race</code> groups. Note that this metric does not depend on the true outcome value, <code>readmitted</code>. The interests of a stakeholder who would like to see additional care resources provisioned at the same rate across <code>race</code> groups, even if the actual need for those resources differs among groups, are represented by this metric. As demographic parity is broadly accepted as part of a legal definition of machine learning fairness, hospital systems might consider this metric to protect themselves legally <span class="citation" data-cites="ecfr">(<a href="#ref-ecfr" role="doc-biblioref">1607.4, n.d.</a>)</span>.</p></li>
</ul>
<p>For each of the above metrics, values closer to zero indicate that a model is more fair.</p>
<p>The above three metrics are defined specifically with fairness in mind. By another view of fairness, though, <code><a href="https://yardstick.tidymodels.org/reference/accuracy.html">accuracy()</a></code> and <code><a href="https://yardstick.tidymodels.org/reference/roc_auc.html">roc_auc()</a></code> are <em>also</em> fairness metrics. Some stakeholders may believe that the most performant model regardless of group membership—i.e. the model that predicts readmission most accurately across groups—is the most fair model.</p>
<p>To evaluate each of these metrics against the specified workflows, we create a metric set like so:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">m_set</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://yardstick.tidymodels.org/reference/metric_set.html">metric_set</a></span><span class="op">(</span></span>
<span>    <span class="va">accuracy</span>,</span>
<span>    <span class="va">roc_auc</span>,</span>
<span>    <span class="fu"><a href="https://yardstick.tidymodels.org/reference/equal_opportunity.html">equal_opportunity</a></span><span class="op">(</span><span class="va">race</span><span class="op">)</span>,</span>
<span>    <span class="fu"><a href="https://yardstick.tidymodels.org/reference/equalized_odds.html">equalized_odds</a></span><span class="op">(</span><span class="va">race</span><span class="op">)</span>,</span>
<span>    <span class="fu"><a href="https://yardstick.tidymodels.org/reference/demographic_parity.html">demographic_parity</a></span><span class="op">(</span><span class="va">race</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">m_set</span></span>
<span><span class="co">#&gt; A metric set, consisting of:</span></span>
<span><span class="co">#&gt; - `accuracy()`, a class metric                 | direction: maximize</span></span>
<span><span class="co">#&gt; - `roc_auc()`, a probability metric            | direction: maximize</span></span>
<span><span class="co">#&gt; - `equal_opportunity(race)()`, a class metric  | direction: minimize,</span></span>
<span><span class="co">#&gt; group-wise on: race</span></span>
<span><span class="co">#&gt; - `equalized_odds(race)()`, a class metric     | direction: minimize,</span></span>
<span><span class="co">#&gt; group-wise on: race</span></span>
<span><span class="co">#&gt; - `demographic_parity(race)()`, a class metric | direction: minimize,</span></span>
<span><span class="co">#&gt; group-wise on: race</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The first two inputs, <code><a href="https://yardstick.tidymodels.org/reference/accuracy.html">accuracy()</a></code> and <code><a href="https://yardstick.tidymodels.org/reference/roc_auc.html">roc_auc()</a></code>, are standard <a href="https://yardstick.tidymodels.org">yardstick</a> metrics. The latter three are also yardstick metrics like any other, though are created using the <a href="https://yardstick.tidymodels.org/reference/new_groupwise_metric.html"><em>metric factories</em></a> <code><a href="https://yardstick.tidymodels.org/reference/equal_opportunity.html">equal_opportunity()</a></code>, <code><a href="https://yardstick.tidymodels.org/reference/equalized_odds.html">equalized_odds()</a></code>, and <code><a href="https://yardstick.tidymodels.org/reference/demographic_parity.html">demographic_parity()</a></code>. When passed a data-column, metric factories output yardstick metrics.</p>
</div>
</div>
</section><section id="evaluation" class="level3"><h3 class="anchored" data-anchor-id="evaluation">Evaluation</h3>
<p>We can now evaluate the workflows we’ve defined against resamples using our metric set. The <code><a href="https://workflowsets.tidymodels.org/reference/workflow_map.html">workflow_map()</a></code> function will call <code><a href="https://tune.tidymodels.org/reference/tune_grid.html">tune_grid()</a></code> on each workflow:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">wflow_set_fit</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu"><a href="https://workflowsets.tidymodels.org/reference/workflow_map.html">workflow_map</a></span><span class="op">(</span></span>
<span>    <span class="va">wflow_set</span>, </span>
<span>    verbose <span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>    seed <span class="op">=</span> <span class="fl">1</span>, </span>
<span>    metrics <span class="op">=</span> <span class="va">m_set</span>,</span>
<span>    resamples <span class="op">=</span> <span class="va">readmission_folds</span></span>
<span>  <span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>A fitted workflow set looks just like the unfitted workflow set we saw previously, except that information on the tuning process is now stored in the <code>option</code> and <code>result</code> variables for each modeling workflow:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">wflow_set_fit</span></span>
<span><span class="co">#&gt; # A workflow set/tibble: 6 × 4</span></span>
<span><span class="co">#&gt;   wflow_id info             option    result   </span></span>
<span><span class="co">#&gt;   &lt;chr&gt;    &lt;list&gt;           &lt;list&gt;    &lt;list&gt;   </span></span>
<span><span class="co">#&gt; 1 basic_lr &lt;tibble [1 × 4]&gt; &lt;opts[2]&gt; &lt;rsmp[+]&gt;</span></span>
<span><span class="co">#&gt; 2 basic_bt &lt;tibble [1 × 4]&gt; &lt;opts[2]&gt; &lt;tune[+]&gt;</span></span>
<span><span class="co">#&gt; 3 basic_nn &lt;tibble [1 × 4]&gt; &lt;opts[2]&gt; &lt;tune[+]&gt;</span></span>
<span><span class="co">#&gt; 4 age_lr   &lt;tibble [1 × 4]&gt; &lt;opts[2]&gt; &lt;rsmp[+]&gt;</span></span>
<span><span class="co">#&gt; 5 age_bt   &lt;tibble [1 × 4]&gt; &lt;opts[2]&gt; &lt;tune[+]&gt;</span></span>
<span><span class="co">#&gt; 6 age_nn   &lt;tibble [1 × 4]&gt; &lt;opts[2]&gt; &lt;tune[+]&gt;</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
</section></section><section id="model-selection" class="level2"><h2 class="anchored" data-anchor-id="model-selection">Model Selection</h2>
<p>Now that we’ve evaluated a number of models with a variety of metrics, we can explore the results to determine our optimal model. Beginning with a quick exploratory plot of the distributions of our metrics:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">wflow_set_fit</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://tune.tidymodels.org/reference/collect_predictions.html">collect_metrics</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html">pivot_wider</a></span><span class="op">(</span></span>
<span>    id_cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">wflow_id</span>, <span class="va">.config</span><span class="op">)</span>, </span>
<span>    names_from <span class="op">=</span> <span class="va">.metric</span>, </span>
<span>    values_from <span class="op">=</span> <span class="va">mean</span></span>
<span>  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">wflow_id</span>, <span class="va">.config</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu">ggpairs</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.text.x <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>angle <span class="op">=</span> <span class="fl">45</span>, vjust <span class="op">=</span> <span class="fl">.8</span>, hjust <span class="op">=</span> <span class="fl">.9</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="figs/plot-wflow-set-fit-corr-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>The fairness metrics <code><a href="https://yardstick.tidymodels.org/reference/demographic_parity.html">demographic_parity()</a></code>, <code><a href="https://yardstick.tidymodels.org/reference/equal_opportunity.html">equal_opportunity()</a></code>, and <code><a href="https://yardstick.tidymodels.org/reference/equalized_odds.html">equalized_odds()</a></code> all take values very close to zero for many models. Also, the metric values are highly correlated with each other, including correlations between fairness metrics and the more general-purpose performance metrics. That is, the most performant models also seem to be among the most fair.</p>
<p>More concretely, we can rank the model configurations to examine only the most performant models:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://workflowsets.tidymodels.org/reference/rank_results.html">rank_results</a></span><span class="op">(</span><span class="va">wflow_set_fit</span>, rank_metric <span class="op">=</span> <span class="st">"roc_auc"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">.metric</span> <span class="op">==</span> <span class="st">"roc_auc"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 42 × 9</span></span>
<span><span class="co">#&gt;    wflow_id .config         .metric  mean std_err     n preprocessor model  rank</span></span>
<span><span class="co">#&gt;    &lt;chr&gt;    &lt;chr&gt;           &lt;chr&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;int&gt; &lt;chr&gt;        &lt;chr&gt; &lt;int&gt;</span></span>
<span><span class="co">#&gt;  1 age_bt   Preprocessor1_… roc_auc 0.605 0.00424    10 recipe       boos…     1</span></span>
<span><span class="co">#&gt;  2 basic_bt Preprocessor1_… roc_auc 0.605 0.00423    10 recipe       boos…     2</span></span>
<span><span class="co">#&gt;  3 age_bt   Preprocessor1_… roc_auc 0.604 0.00378    10 recipe       boos…     3</span></span>
<span><span class="co">#&gt;  4 age_bt   Preprocessor1_… roc_auc 0.603 0.00421    10 recipe       boos…     4</span></span>
<span><span class="co">#&gt;  5 basic_bt Preprocessor1_… roc_auc 0.603 0.00410    10 recipe       boos…     5</span></span>
<span><span class="co">#&gt;  6 basic_bt Preprocessor1_… roc_auc 0.603 0.00436    10 recipe       boos…     6</span></span>
<span><span class="co">#&gt;  7 age_bt   Preprocessor1_… roc_auc 0.602 0.00372    10 recipe       boos…     7</span></span>
<span><span class="co">#&gt;  8 basic_nn Preprocessor1_… roc_auc 0.602 0.00403    10 recipe       bag_…     8</span></span>
<span><span class="co">#&gt;  9 age_nn   Preprocessor1_… roc_auc 0.600 0.00431    10 recipe       bag_…     9</span></span>
<span><span class="co">#&gt; 10 age_nn   Preprocessor1_… roc_auc 0.600 0.00412    10 recipe       bag_…    10</span></span>
<span><span class="co">#&gt; # ℹ 32 more rows</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>Almost all of the most performant model configurations arise from the boosted tree modeling workflow. Let’s examine the results for specifically the modeling workflow that encodes age as a number more thoroughly:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="va">wflow_set_fit</span>, id <span class="op">=</span> <span class="st">"age_bt"</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="figs/autoplot-age-bt-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>The learning rate <code>learn_rate</code> seems to have a more pronounced effect on the results metrics than the number of randomly selected predictors <code>mtry</code>. As before, we see that the most performant models with respect to <code><a href="https://yardstick.tidymodels.org/reference/roc_auc.html">roc_auc()</a></code> also tend to be the most fair according to our fairness metrics. Further, the values of each of the fairness metrics plotted above seem highly correlated.</p>
<p>From the perspective of a practitioner hoping to satisfy various stakeholders, the fact that these metrics are highly correlated makes the model selection process much easier. We can choose one fairness metric that we’d like to optimize for, and likely end up with a near-optimal configuration for the other metrics as a byproduct.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In machine learning fairness, “impossibility theorems” show that fairness definitions “are not mathematically or morally compatible in general” <span class="citation" data-cites="mitchell2021">(<a href="#ref-mitchell2021" role="doc-biblioref">Mitchell et al. 2021</a>)</span>. More concretely, unless we live in a world with no inequality, there is no way to satisfy many definitions of fairness at once. However, recent research emphasizes that near-fairness among more limited sets of metrics, like the three we’ve used here, is both possible and relevant <span class="citation" data-cites="bell2023">(<a href="#ref-bell2023" role="doc-biblioref">Bell et al. 2023</a>)</span>.</p>
</div>
</div>
<p>To choose a model that performs well both with respect to a typical performance metric like <code><a href="https://yardstick.tidymodels.org/reference/roc_auc.html">roc_auc()</a></code> and the fairness metrics we’ve chosen, we will make use of <a href="https://www.tidyverse.org/blog/2023/05/desirability2/">desirability functions</a>, which allow us to optimize based on multiple metrics at once.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">best_params</span> <span class="op">&lt;-</span></span>
<span>  <span class="co"># extract the tuning results for the boosted tree model</span></span>
<span>  <span class="fu"><a href="https://workflowsets.tidymodels.org/reference/extract_workflow_set_result.html">extract_workflow_set_result</a></span><span class="op">(</span><span class="va">wflow_set_fit</span>, <span class="st">"age_bt"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="co"># collect the metrics associated with it</span></span>
<span>  <span class="fu"><a href="https://tune.tidymodels.org/reference/collect_predictions.html">collect_metrics</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="co"># pivot the metrics so that each is in a column</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html">pivot_wider</a></span><span class="op">(</span></span>
<span>    id_cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">mtry</span>, <span class="va">learn_rate</span><span class="op">)</span>, </span>
<span>    names_from <span class="op">=</span> <span class="va">.metric</span>, </span>
<span>    values_from <span class="op">=</span> <span class="va">mean</span></span>
<span>  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    <span class="co"># higher roc values are better; detect max and min from the data</span></span>
<span>    d_roc     <span class="op">=</span> <span class="fu">d_max</span><span class="op">(</span><span class="va">roc_auc</span>, use_data <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>    <span class="co"># lower equalized odds are better; detect max and min from the data</span></span>
<span>    d_e_odds  <span class="op">=</span> <span class="fu">d_min</span><span class="op">(</span><span class="va">equalized_odds</span>, use_data <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>    <span class="co"># compute overall desirability based on d_roc and d_e_odds</span></span>
<span>    d_overall <span class="op">=</span> <span class="fu">d_overall</span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/across.html">across</a></span><span class="op">(</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with</a></span><span class="op">(</span><span class="st">"d_"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="co"># pick the model with the highest desirability value</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_max</a></span><span class="op">(</span><span class="va">d_overall</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>The result is a tibble giving the parameter values that resulted in the best model:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">best_params</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 10</span></span>
<span><span class="co">#&gt;    mtry learn_rate accuracy demographic_parity equal_opportunity equalized_odds</span></span>
<span><span class="co">#&gt;   &lt;int&gt;      &lt;dbl&gt;    &lt;dbl&gt;              &lt;dbl&gt;             &lt;dbl&gt;          &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1     7    0.00456    0.912                  0                 0              0</span></span>
<span><span class="co">#&gt; # ℹ 4 more variables: roc_auc &lt;dbl&gt;, d_roc &lt;dbl&gt;, d_e_odds &lt;dbl&gt;,</span></span>
<span><span class="co">#&gt; #   d_overall &lt;dbl&gt;</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>We can use that tibble to finalize a workflow that we’ll use to generate our final model fit:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">final_model_config</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://hardhat.tidymodels.org/reference/hardhat-extract.html">extract_workflow</a></span><span class="op">(</span><span class="va">wflow_set_fit</span>, <span class="st">"age_bt"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://tune.tidymodels.org/reference/finalize_model.html">finalize_workflow</a></span><span class="op">(</span><span class="va">best_params</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>Finally, generating our final model fit:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">final_model</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu"><a href="https://tune.tidymodels.org/reference/last_fit.html">last_fit</a></span><span class="op">(</span><span class="va">final_model_config</span>, <span class="va">readmission_splits</span>, metrics <span class="op">=</span> <span class="va">m_set</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>We can see the metrics associated with the final fit using <code><a href="https://tune.tidymodels.org/reference/collect_predictions.html">collect_metrics()</a></code>, just as with a tuning result:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://tune.tidymodels.org/reference/collect_predictions.html">collect_metrics</a></span><span class="op">(</span><span class="va">final_model</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 5 × 5</span></span>
<span><span class="co">#&gt;   .metric            .estimator .estimate .by   .config             </span></span>
<span><span class="co">#&gt;   &lt;chr&gt;              &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;               </span></span>
<span><span class="co">#&gt; 1 accuracy           binary         0.912 &lt;NA&gt;  Preprocessor1_Model1</span></span>
<span><span class="co">#&gt; 2 equal_opportunity  binary         0     race  Preprocessor1_Model1</span></span>
<span><span class="co">#&gt; 3 equalized_odds     binary         0     race  Preprocessor1_Model1</span></span>
<span><span class="co">#&gt; 4 demographic_parity binary         0     race  Preprocessor1_Model1</span></span>
<span><span class="co">#&gt; 5 roc_auc            binary         0.602 &lt;NA&gt;  Preprocessor1_Model1</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>The model we’ve selected has near-fairness with respect to the set of metrics we’ve chosen here. The accuracy of the model is 91.16%, quite similar to the accuracy that would result if the model just always predicted a patient would not readmit (91.2%). The <code><a href="https://yardstick.tidymodels.org/reference/roc_auc.html">roc_auc()</a></code> value 0.602 indicates that the model indeed correctly predicts readmission in some cases, though still has a lot of room for improvement. A further analysis of these models might measure performance using a metric that specifically evaluates predictions on observations from the minority class—as in, patients that did actually readmit—like <a href="https://yardstick.tidymodels.org/reference/sens.html?q=sens#details"><code>sens()</code></a>.</p>
<p>Extracting the model fit from the <code>last_fit</code> object:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">final_model_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://hardhat.tidymodels.org/reference/hardhat-extract.html">extract_workflow</a></span><span class="op">(</span><span class="va">final_model</span><span class="op">)</span></span></code></pre></div>
<button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button>
</div>
</div>
<p>The <code>final_model_fit</code> object is now ready to predict on new data! Models generated with tidymodels are easily versioned, deployed, and monitored using the vetiver framework; learn more about the framework on the <a href="https://vetiver.rstudio.com/get-started/">vetiver website</a>.</p>
<p>In this article, we’ve demonstrated a fairness-oriented modeling analysis. Modeling with fairness in mind is not simply a numerical optimization problem, but a holistic process of examining the moral meanings of fairness in our problem context and how they are represented—or not represented—by various mathematical notions of fairness.</p>
<p>While this analysis allowed us to train models that are near-fair with respect to a limited set of fairness metrics, it leaves many questions to be answered about the impacts of using such a model. Among other things:</p>
<ul>
<li>We’ve only evaluated the fairness of the model with <code>race</code> in mind. We also have information on the patient’s <code>sex</code>. Could this model behave unfairly with respect to the patient’s <code>sex</code>? How about with respect to the intersections of <code>race</code> and <code>sex</code>? A growing body of research shows us that black women experience pronounced discrimination as patients <span class="citation" data-cites="johnson2019 okoro2020 gopal2021">(<a href="#ref-johnson2019" role="doc-biblioref">Johnson et al. 2019</a>; <a href="#ref-okoro2020" role="doc-biblioref">Okoro et al. 2020</a>; <a href="#ref-gopal2021" role="doc-biblioref">Gopal et al. 2021</a>)</span>.</li>
<li>The categorizations of <code>race</code> and <code>sex</code> that we have access to are coarse. Race/ethnicity and sex/gender are richly and diversely experienced, and the limited set of categories that patients are presented with (or unknowingly assigned to) in healthcare contexts are only a proxy for how a patient may experience them.</li>
<li>We’ve used <em>readmission</em> as a proxy for <em>need for additional care</em>. What factors might influence whether a patient willingly readmits? Or is admitted to the hospital in the first place? Note, especially, the disproportionate financial burden of healthcare for poorer patients.</li>
<li>We don’t know how the predictions resulting from this model will be used by practitioners or trusted by patients. The outputs of the model, of course, should be evaluated in conjunction with other evidence collected by a healthcare team throughout a patient’s stay. Knowing this, though, will the model’s outputs be differently interpreted for different groups in the patient population? For example, would a positive prediction of readmission be considered more seriously as evidence for needed additional care for a white man than for others? Further, given historical exploitation and unethical practice, would protected groups believe that algorithmic recommendation for additional care is likely discriminatory and mistrust the recommendations offered to them? <span class="citation" data-cites="rajkomar2018">(See <a href="#ref-rajkomar2018" role="doc-biblioref">Rajkomar et al. 2018</a>.)</span>
</li>
</ul>
<p>Machine learning models can both have significant positive impacts on our lives and at the same time cause significant harms. Given the tremendous reach of these models in our society, efforts to include fairness as a criteria for evaluating machine learning models are as necessary as ever.</p>
</section><section id="session-info" class="level2"><h2 class="anchored" data-anchor-id="session-info">Session information</h2>
<div class="cell" data-layout-align="center">
<pre><code>#&gt; ─ Session info ─────────────────────────────────────────────────────
#&gt;  version  R version 4.5.2 (2025-10-31)
#&gt;  language (EN)
#&gt;  date     2026-04-22
#&gt;  pandoc   3.8.3
#&gt;  quarto   1.9.35
#&gt; 
#&gt; ─ Packages ─────────────────────────────────────────────────────────
#&gt;  package         version date (UTC)
#&gt;  baguette        1.1.0   2025-01-28
#&gt;  broom           1.0.12  2026-01-27
#&gt;  desirability2   0.2.0   2025-08-22
#&gt;  dials           1.4.3   2026-04-11
#&gt;  dplyr           1.2.1   2026-04-03
#&gt;  GGally          2.4.0   2025-08-23
#&gt;  ggplot2         4.0.3   2026-04-22
#&gt;  infer           1.1.0   2025-12-18
#&gt;  parsnip         1.5.0   2026-04-09
#&gt;  purrr           1.2.2   2026-04-10
#&gt;  readmission     0.1.0   2023-12-07
#&gt;  recipes         1.3.2   2026-04-02
#&gt;  rlang           1.2.0   2026-04-06
#&gt;  rsample         1.3.2   2026-01-30
#&gt;  tibble          3.3.1   2026-01-11
#&gt;  tidymodels      1.4.1   2025-09-08
#&gt;  tune            2.1.0   2026-04-17
#&gt;  workflows       1.3.0   2025-08-27
#&gt;  yardstick       1.4.0   2026-04-07
#&gt; 
#&gt; ────────────────────────────────────────────────────────────────────</code></pre>
</div>



</section><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-ecfr" class="csl-entry" role="listitem">
1607.4, 29 CFR §. n.d. <em>Information on Impact</em>.
</div>
<div id="ref-bell2023" class="csl-entry" role="listitem">
Bell, Andrew, Lucius Bynum, Nazarii Drushchak, Tetiana Zakharchenko, Lucas Rosenblatt, and Julia Stoyanovich. 2023. <span>“The Possibility of Fairness: Revisiting the Impossibility Theorem in Practice.”</span> <em>Proceedings of the 2023 ACM Conference on Fairness, Accountability, and Transparency</em> (New York, NY, USA), FAccT ’23, 400–422. <a href="https://doi.org/10.1145/3593013.3594007">https://doi.org/10.1145/3593013.3594007</a>.
</div>
<div id="ref-gopal2021" class="csl-entry" role="listitem">
Gopal, Dipesh P, Ula Chetty, Patrick O’Donnell, Camille Gajria, and Jodie Blackadder-Weinstein. 2021. <span>“Implicit Bias in Healthcare: Clinical Practice, Research and Decision Making.”</span> <em>Future Healthcare Journal</em> 8 (1): 40.
</div>
<div id="ref-johnson2019" class="csl-entry" role="listitem">
Johnson, Jasmine D, Ifeyinwa V Asiodu, Christine P McKenzie, et al. 2019. <span>“Racial and Ethnic Inequities in Postpartum Pain Evaluation and Management.”</span> <em>Obstetrics &amp; Gynecology</em> 134 (6): 1155–62.
</div>
<div id="ref-kuhn2022" class="csl-entry" role="listitem">
Kuhn, Max, and Julia Silge. 2022. <em>Tidy Modeling with r</em>. "O’Reilly Media, Inc.".
</div>
<div id="ref-mitchell2021" class="csl-entry" role="listitem">
Mitchell, Shira, Eric Potash, Solon Barocas, Alexander D’Amour, and Kristian Lum. 2021. <span>“Algorithmic Fairness: Choices, Assumptions, and Definitions.”</span> <em>Annual Review of Statistics and Its Application</em> 8 (1): 141–63. <a href="https://doi.org/10.1146/annurev-statistics-042720-125902">https://doi.org/10.1146/annurev-statistics-042720-125902</a>.
</div>
<div id="ref-obermeyer2019" class="csl-entry" role="listitem">
Obermeyer, Ziad, Brian Powers, Christine Vogeli, and Sendhil Mullainathan. 2019. <span>“Dissecting Racial Bias in an Algorithm Used to Manage the Health of Populations.”</span> <em>Science</em> 366 (6464): 447–53. <a href="https://doi.org/10.1126/science.aax2342">https://doi.org/10.1126/science.aax2342</a>.
</div>
<div id="ref-okoro2020" class="csl-entry" role="listitem">
Okoro, Olihe N, Lisa A Hillman, and Alina Cernasev. 2020. <span>“<span>‘We Get Double Slammed!’</span>: Healthcare Experiences of Perceived Discrimination Among Low-Income African-American Women.”</span> <em>Women’s Health</em> 16: 1745506520953348.
</div>
<div id="ref-omi1994" class="csl-entry" role="listitem">
Omi, Michael, and Howard Winant. 1994. <em>Racial Formation in the United States</em>. Second. Routledge.
</div>
<div id="ref-rajkomar2018" class="csl-entry" role="listitem">
Rajkomar, Alvin, Michaela Hardt, Michael D Howell, Greg Corrado, and Marshall H Chin. 2018. <span>“Ensuring Fairness in Machine Learning to Advance Health Equity.”</span> <em>Annals of Internal Medicine</em> 169 (12): 866–72.
</div>
<div id="ref-strack2014" class="csl-entry" role="listitem">
<span class="nocase">Strack, Beata, Jonathan P DeShazo, Chris Gennings, et al.</span> 2014. <span>“Impact of HbA1c Measurement on Hospital Readmission Rates: Analysis of 70,000 Clinical Database Patient Records.”</span> <em>BioMed Research International</em> 2014.
</div>
</div></section></div></main><!-- /main --><!-- plausible --><script async="" defer data-domain="tidymodels.org,all.tidymodels.org" src="https://plausible.io/js/plausible.js"></script><div class="section resources">
  <div class="resourcesTitle">Resources</div>
  <div class="event">
    <div class="eventTitle">
      <a href="../../../find/"><i class="fas fa-search fa-xs"></i>  Find</a>
    </div>
    <div class="eventDetails">Explore searchable tables of all tidymodels packages and functions.</div>
  </div>
  <div class="event">
    <div class="eventTitle">
      <a href="../../../books/"><i class="fas fa-book-open fa-xs"></i>  Books</a>
    </div>
    <div class="eventDetails">Study up on statistics and modeling with our comprehensive books.</div>
  </div>
  <div class="event">
    <div class="eventTitle">
      <a href="../../../cheatsheets/"><i class="fas fa-file-alt fa-xs"></i>  Cheatsheets</a>
    </div>
    <div class="eventDetails">Quick reference guides for tidymodels packages.</div>
  </div>
  <div class="event">
    <div class="eventTitle">
      <a href="https://www.tidyverse.org/tags/tidymodels/" target="_blank"><i class="fas fa-bullhorn fa-xs"></i>  News</a>
    </div>
    <div class="eventDetails">Hear the latest about tidymodels packages at the <a href="https://www.tidyverse.org/tags/tidymodels/">tidyverse blog</a>.</div>
  </div>
</div>

<script>
  sidebar = document.querySelector('#quarto-margin-sidebar');
  resources = document.querySelector('.resources');
  sidebar.appendChild(resources);
</script><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/www\.tidymodels\.org");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Proudly supported by <a href="https://posit.co"><img src="https://posit.co/wp-content/themes/Posit/assets/images/posit-logo-2024.svg" class="img-fluid" alt="Posit" width="65"></a></p>
</div>   
    <div class="nav-footer-center">
       
    <div class="toc-actions d-sm-block d-md-none"><ul>
<li><a href="https://github.com/tidymodels/tidymodels.org/edit/main/learn/work/fairness-readmission/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li>
<li><a href="https://github.com/tidymodels/tidymodels.org/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li>
</ul></div>
</div>
    <div class="nav-footer-right">
<p><a onclick="window.scrollTo({ top: 0, behavior: 'smooth' }); return false;" role="button"> <i class="fa-solid fa-chevron-up" aria-label="chevron-up"></i> </a></p>
</div>
  </div>
</footer>
</body>
</html>
