packages <- c(
  "abind",
  "quarto",
  "r-lib/revdepcheck",
  "desc",
  "urlchecker",
  "extrasteps",
  "readr",
  "tidyverse",
  "rattle",
  "parttree",
  "AmesHousing",
  "aorsf",
  "AppliedPredictiveModeling",
  "baguette",
  "betacal",
  "blogdown",
  "broom.mixed",
  "brulee",
  "C50",
  "censored",
  "Cubist",
  "desirability2",
  "detectors",
  "devtools",
  "dials",
  "discrim",
  "doMC",
  "doParallel",
  "dotwhisker",
  "embed",
  "filtro",
  "forecast",
  "fs",
  "furrr",
  "future",
  "GGally",
  "glmnet",
  "glue",
  "htmlwidgets",
  "kableExtra",
  "keras3",
  "kernlab",
  "klaR",
  "leaflet",
  "lobstr",
  "mda",
  "mlbench",
  "modeldata",
  "modeldatatoo",
  "modeltime",
  "nycflights13",
  "parsnip",
  "partykit",
  "pkgdown",
  "pls",
  "plsmod",
  "poissonreg",
  "probably",
  "prodlim",
  "quantregForest",
  "randomForest",
  "ranger",
  "readmission",
  "rlang",
  "ROSE",
  "rpart.plot",
  "rsample",
  "rstanarm",
  "rules",
  "scales",
  "sessioninfo",
  "skimr",
  "slider",
  "sparsevctrs",
  "spatialsample",
  "stacks",
  "stopwords",
  "stringr",
  "sweep",
  "text2vec",
  "textrecipes",
  "themis",
  "tidymodels",
  "tidyposterior",
  "tictoc",
  "timetk",
  "torch",
  "tune",
  "vip",
  "zoo",
  "DT",
  "mars",
  "earth",
  "dbarts",
  "catboost/catboost/catboost/R-package",
  "sda",
  "sparsediscrim",
  "LiblineaR",
  "naivebayes",
  "xgboost",
  "xrf",
  "yaml",
  "pscl",
  "coin",
  "pec",
  "flexsurv",
  "agua",
  "bonsai",
  "lightgbm",
  "grf",
  "h2o",
  "kknn",
  "mboost",
  "quantreg",
  "multilevelmod",
  "sparklyr",
  "HSAUR3",
  "lme4",
  "survival",
  "gee",
  "mixOmics"
)

# Reuse the same install logic as the incremental re-render scripts, so a
# full install also gets the special-case handling (vip's GitHub source,
# mixOmics via Bioconductor, torch/keras/Spark backends, rstanarm rebuilds)
# instead of just a bare pak::pak() call.
source(here::here("R/install_packages.R"))
install_packages(packages)

# Manually check for dev versions
# sub("rstudio/", "", packages) |>
#   sub("/catboost/catboost/R-package", "", x = _) |>
#   setdiff(c()) |>
#   sapply(packageVersion) |>
#   purrr::keep(\(x) any(x >= 9000))

